import {test,expect} from '@playwright/test';
import {testApp} from '../scripts/test-app.mjs';
import {defaultState} from '../client/src/quote/data/configurators.js';
import {DEFAULT_PRICE_BOOK as pb} from '../client/src/quote/data/priceBook.js';
import {buildLineState} from '../client/src/quote/lib/estimate.js';
import {computeTotals} from '../client/src/quote/lib/quote.js';
let app;
test.beforeAll(async()=>{app=await testApp({serve:true});app.sqlite.prepare("UPDATE users SET credential_type='password' WHERE role='owner'").run();});
test.afterAll(async()=>app.close());
test('Package issuing requires cost review and preserves public totals',async()=>{
 const state={...defaultState('carport'),pricingMode:'package',gableFrame:'truss',costMaterials:5000,costLabor:2000};
 const pricing={taxPct:8.25,discountPct:10};
 const lines=buildLineState('carport',state,pb,{}),totals=computeTotals(lines,pricing);
 const make=async(s)=>app.api('/api/quotes','POST',{type:'carport',customerName:'Package fixture',totalCents:Math.round(totals.total*100),payload:{type:'carport',state:s,...pricing,priceBookSnapshot:pb,customer:{name:'Package fixture'}}},app.owner);
 let q=await make(state);expect(q.status).toBe(201);
 expect((await app.api(`/api/quotes/${q.data.id}/share`,'POST',{},app.owner)).status).toBe(400);
 q=await make({...state,costReviewKey:lines.carportPricing.reviewKey});expect(q.status).toBe(201);
 const shared=await app.api(`/api/quotes/${q.data.id}/share`,'POST',{},app.owner);expect(shared.status,JSON.stringify(shared.data)).toBe(200);
 const doc=await app.api(`/api/public/quote/${shared.data.token}`);expect(doc.status).toBe(200);
 expect(JSON.stringify(doc.data)).not.toContain('costMaterials');
 expect(doc.data.quote.doc.totals.totalCents).toBe(1082500);
 expect(doc.data.quote.lines.reduce((sum,l)=>sum+l.amountCents,0)).toBe(1082500);
});
test('New carport package is editable and saves on mobile',async({page})=>{
 test.setTimeout(90000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 await page.addInitScript(token=>{if(location.hostname==='127.0.0.1')localStorage.setItem('wpt-auth-token',token)},app.owner);
 await page.goto(app.base+'/#/crm/quotes');
 await page.getByLabel('Customer name',{exact:true}).fill('Carport mobile fixture');
 await page.locator('.type-card').filter({has:page.getByRole('heading',{name:'Carport',exact:true})}).click();
 await expect(page.getByRole('heading',{name:'1. Size',exact:true})).toBeVisible();
 await page.getByLabel('Add concrete slab',{exact:true}).check();
 await page.getByRole('button',{name:/Next: price/i}).click();
 await expect(page.getByLabel('Installed price / sq ft',{exact:true})).toHaveValue('25');
 await page.getByLabel('Installed price / sq ft',{exact:true}).fill('28');
 await page.getByText('Job costs & profit',{exact:false}).click();
 await page.getByLabel('Materials & waste',{exact:true}).fill('4000');
 await page.getByLabel('Shop & installation labor',{exact:true}).fill('2000');
 await page.getByLabel('Subcontractors / concrete',{exact:true}).fill('2500');
 await page.getByLabel('I reviewed all job costs and allowances',{exact:true}).check();
 await expect(page.locator('.draft-status')).toHaveText('Saved');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 const saved=app.sqlite.prepare("SELECT payload FROM quotes WHERE customer_name=? ORDER BY id DESC LIMIT 1").get('Carport mobile fixture');
 expect(JSON.parse(saved.payload).state.packageRate).toBe('28');
 expect(JSON.parse(saved.payload).state.costReviewKey).toBeTruthy();
 await page.screenshot({path:'test-results/carport-package-mobile.png',fullPage:true});
 expect(errors).toEqual([]);
});
