import {test,expect} from '@playwright/test';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {testApp} from '../scripts/test-app.mjs';
let app;
test.beforeAll(async()=>{app=await testApp({serve:true});app.sqlite.prepare("UPDATE users SET credential_type='password' WHERE role='owner'").run();Object.assign(process.env,{OWNER_EMAIL:'owner@example.test',MAIL_FROM:'preview@example.test',RESEND_API_KEY:'test-only-key'});});
test.afterAll(async()=>app.close());
test('Save and open includes pending text, and replacing a model retains its link',async({page,context})=>{
  await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
  await page.goto(app.base+'/#/crm/previews');
  await page.getByRole('button',{name:'New preview',exact:true}).click();const dialog=page.getByRole('dialog');
  await dialog.getByLabel('Project title',{exact:true}).fill('Replacement fixture');
  await dialog.getByRole('button',{name:'Create preview',exact:true}).click();
  await dialog.getByLabel('3D model',{exact:true}).setInputFiles(fileURLToPath(new URL('../server/preview-seeds/kalkat-5.glb',import.meta.url)));
  await dialog.getByRole('button',{name:'Add option',exact:true}).click();await dialog.getByRole('button',{name:'Enable customer link'}).click();
  const link=await dialog.getByLabel('Customer preview link').inputValue();
  await dialog.getByLabel('Short description',{exact:true}).fill('Changed description');
  await dialog.getByLabel('depth',{exact:true}).fill('40 ft');
  await dialog.getByLabel('Details for the customer').fill('Changed notes');
  await expect(dialog.getByRole('region',{name:'Live customer preview'})).toContainText('Changed description');
  await expect(dialog.getByRole('region',{name:'Live customer preview'})).toContainText('Changed notes');
  await context.route('https://www.cjmmetals.com/p/**',r=>r.fulfill({body:'Preview fixture'}));
  const popupPromise=page.waitForEvent('popup');await dialog.getByRole('button',{name:'Save & open preview',exact:true}).click();const popup=await popupPromise;
  await expect(popup).toHaveURL(new RegExp(link+'\\?owner=1&v=\\d+'));
  let saved=(await app.api('/api/customer-previews','GET',undefined,app.owner)).data.find(p=>p.shortUrl===link);
  expect(saved.depth).toBe('40 ft');
  expect((await app.api('/api/public/customer-previews/'+saved.url.split('/').at(-1),'GET',undefined,undefined,{'X-Lead-Key':'test-intake-key'})).data.depth).toBe('40 ft');
  expect(saved.description).toBe('Changed description');expect(saved.note).toBe('Changed notes');await popup.close();
  await dialog.getByLabel('Replace model: kalkat-5',{exact:true}).setInputFiles(fileURLToPath(new URL('../server/preview-seeds/kalkat-7.glb',import.meta.url)));
  await dialog.getByRole('button',{name:'Publish design updates'}).click();
  await expect(dialog.getByRole('button',{name:'Restore previous model'})).toBeVisible();
  await expect(dialog.getByLabel('Customer preview link')).toHaveValue(link);
  saved=(await app.api('/api/customer-previews','GET',undefined,app.owner)).data.find(p=>p.shortUrl===link);expect(saved.options[0].revision).toBe(2);expect(saved.options).toHaveLength(1);
  await dialog.getByRole('button',{name:'Restore previous model'}).click();
  await dialog.getByRole('button',{name:'Publish design updates'}).click();
  await expect.poll(async()=>(await app.api('/api/customer-previews','GET',undefined,app.owner)).data.find(p=>p.shortUrl===link).options[0].revision).toBe(3);
});
test('Owner creates a design preview, adds a model, shares it and reads customer changes',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
  await page.goto(app.base+'/#/crm/previews');
  await expect(page.getByText('Feedback and design acceptance emails go to')).toContainText('owner@example.test');
  await page.getByRole('button',{name:'New preview',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByLabel('Project title',{exact:true}).fill(' Synthetic test gate ');
  await dialog.getByLabel('Short description',{exact:true}).fill('Review this design before your quote.');
  await dialog.getByRole('button',{name:'Create preview',exact:true}).click();
  await expect(dialog.getByLabel('Project title',{exact:true})).toHaveValue('Synthetic test gate');
  await expect(dialog.getByRole('button',{name:'Enable customer link'})).toBeDisabled();
  await dialog.getByLabel('Option name',{exact:true}).fill('5 pipes');
  await dialog.getByLabel('3D model',{exact:true}).setInputFiles(fileURLToPath(new URL('../server/preview-seeds/kalkat-5.glb',import.meta.url)));
  await dialog.getByRole('button',{name:'Add option',exact:true}).click();
  await expect(dialog.getByText('5 pipes',{exact:true})).toBeVisible();
  await dialog.getByRole('button',{name:'Enable customer link'}).click();
  await expect(dialog.getByLabel('Customer preview link')).toHaveValue(/^https:\/\/www\.cjmmetals\.com\/p\/[a-z0-9-]+-[A-Za-z0-9_-]{16}$/);
  const list=(await app.api('/api/customer-previews','GET',undefined,app.owner)).data;
  const p=list.find(x=>x.title==='Synthetic test gate'),token=p.url.split('/').at(-1);
  await dialog.getByLabel('Project title',{exact:true}).fill('Unsaved design change');
  expect((await app.api(`/api/public/customer-previews/${token}/feedback`,'POST',{submissionId:crypto.randomUUID(),optionId:p.options[0].id,message:'Please enlarge the lettering.'},undefined,{'X-Lead-Key':'test-intake-key'})).status).toBe(201);
  await expect(dialog.getByText('Please enlarge the lettering.')).toBeVisible({timeout:10000});
  await expect(dialog.getByText('Email notification queued',{exact:true})).toBeVisible();
  await expect(dialog.getByLabel('Project title',{exact:true})).toHaveValue('Unsaved design change');
  await dialog.getByLabel('Project title',{exact:true}).fill('Synthetic test gate');
  await dialog.getByRole('button',{name:'Close',exact:true}).click();
  const card=page.getByRole('article').filter({hasText:'Synthetic test gate'});
  await expect(card).toContainText('1 customer response');
  await card.getByRole('button',{name:'Manage',exact:true}).click();
  await expect(dialog.getByText('Please enlarge the lettering.')).toBeVisible();
  expect((await app.api(`/api/public/customer-previews/${token}/accept`,'POST',{submissionId:crypto.randomUUID(),optionId:p.options[0].id,version:p.version},undefined,{'X-Lead-Key':'test-intake-key'})).status).toBe(201);
  await expect(dialog.getByText('Design accepted for quoting',{exact:true})).toBeVisible({timeout:10000});
  await dialog.getByRole('button',{name:'Close',exact:true}).click();
  await expect(card).toContainText('Ready for a quote · 5 pipes');
  await expect(card).toContainText('2 customer responses');
  await expect(card.getByRole('link',{name:'Open preview'})).toHaveAttribute('href',p.shortUrl+'?owner=1');
  const activity={visitId:crypto.randomUUID(),version:p.version,seq:1,activeMs:12000,variants:[{id:p.options[0].id,views:1,activeMs:10000,loads:1,loadMs:300,errors:0,gateOpens:2,gateCloses:1,drags:3,zooms:1}],links:{main:1,concrete:0,insulation:0,phone:0,email:0},webglFailed:0,contextLost:0};
  expect((await app.api('/api/public/customer-previews/'+token+'/activity','POST',activity,undefined,{'X-Lead-Key':'test-intake-key','X-Preview-User-Agent':'Chrome/130'})).status).toBe(201);
  await card.getByRole('button',{name:'Customer activity',exact:true}).click();
  await expect(dialog.getByText('Active viewing time',{exact:true}).locator('..')).toContainText('12s');
  await expect(dialog.getByText('Preview visits',{exact:true}).locator('..')).toContainText('1');
  await expect(dialog.locator('section').filter({has:page.getByRole('heading',{name:'Variant interest & interactions'})}).getByText('Gate opens / closes: 2 / 1')).toBeVisible();
  await expect(dialog.getByText('Design accepted for quoting · 5 pipes')).toBeVisible();
  await expect(dialog.getByText('Please enlarge the lettering.')).toBeVisible();
  await dialog.locator('summary').click();
  await expect(dialog.getByText('Links: CJM Metals (1)')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.screenshot({path:'test-results/customer-preview-activity.png',fullPage:true});
  await dialog.getByRole('button',{name:'Close',exact:true}).click();

  await card.getByRole('button',{name:'Manage',exact:true}).click();
  await dialog.getByRole('button',{name:'Disable link',exact:true}).click();
  expect((await app.api(`/api/public/customer-previews/${token}`,'GET',undefined,undefined,{'X-Lead-Key':'test-intake-key'})).status).toBe(404);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.screenshot({path:'test-results/customer-previews-suite.png',fullPage:true});
  expect(errors).toEqual([]);
});


test('Delete removes a preview and disables its customer link',async({page})=>{
 const created=await app.api('/api/customer-previews','POST',{title:'Delete fixture'},app.owner);const preview=created.data;
 app.sqlite.prepare('UPDATE customer_previews SET published=1 WHERE id=?').run(preview.id);
 expect((await app.api(`/api/customer-previews/${preview.id}`,'DELETE',{version:preview.version})).status).toBe(401);
 expect((await app.api(`/api/customer-previews/${preview.id}`,'DELETE',{version:preview.version+1},app.owner)).status).toBe(409);
 await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);await page.goto(app.base+'/#/crm/previews');
 const card=page.locator('article').filter({has:page.getByRole('heading',{name:'Delete fixture',exact:true})});
 await card.getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(card).toBeVisible();
 await card.getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Delete preview',exact:true}).click();await expect(card).toHaveCount(0);
 expect((await app.api('/api/customer-previews','GET',undefined,app.owner)).data.some(p=>p.id===preview.id)).toBe(false);
 const deleted=app.sqlite.prepare('SELECT deleted_at,published FROM customer_previews WHERE id=?').get(preview.id);expect(deleted.deleted_at).toBeGreaterThan(0);expect(deleted.published).toBe(0);
 const token=preview.url.split('/').pop();expect((await app.api(`/api/public/customer-previews/${token}`,'GET')).status).toBe(404);
});


for(const type of ['Gate','Fence','Carport','Pergola','Railing','Table'])test(`${type} exposes customer preview creation above its model`,async({page})=>{
 await page.route('https://www.cjmmetals.com/**',r=>r.fulfill({contentType:'text/html',body:`<script>parent.postMessage({kind:'cjm-preview-ready'},'*')</script>`}));
 await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);await page.goto(app.base+'/#/crm/quotes');
 await page.locator('.type-card').filter({has:page.getByRole('heading',{name:type,exact:true})}).click();
 const button=page.getByRole('button',{name:'Create customer preview',exact:true});await expect(button).toBeEnabled();
 const model=page.locator('.website-product-preview iframe');const a=await button.boundingBox(),b=await model.boundingBox();expect(a.y+a.height).toBeLessThanOrEqual(b.y);
 await button.click();await expect(page.getByLabel('Preview title',{exact:true})).toHaveValue(type+' design');
});
