import {test,expect} from '@playwright/test';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {testApp} from '../scripts/test-app.mjs';
let app;
test.beforeAll(async()=>{app=await testApp({serve:true});app.sqlite.prepare("UPDATE users SET credential_type='password' WHERE role='owner'").run();});
test.afterAll(async()=>app.close());
test('Owner creates a design preview, adds a model, shares it and reads customer changes',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
  await page.goto(app.base+'/#/crm/previews');
  await page.getByRole('button',{name:'New preview',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByLabel('Project title',{exact:true}).fill('Synthetic test gate');
  await dialog.getByLabel('Short description',{exact:true}).fill('Review this design before your quote.');
  await dialog.getByRole('button',{name:'Create preview',exact:true}).click();
  await expect(dialog.getByRole('button',{name:'Enable customer link'})).toBeDisabled();
  await dialog.getByLabel('Option name',{exact:true}).fill('5 pipes');
  await dialog.getByLabel('3D model',{exact:true}).setInputFiles(fileURLToPath(new URL('../server/preview-seeds/kalkat-5.glb',import.meta.url)));
  await dialog.getByRole('button',{name:'Add option',exact:true}).click();
  await expect(dialog.getByText('5 pipes',{exact:true})).toBeVisible();
  await dialog.getByRole('button',{name:'Enable customer link'}).click();
  await expect(dialog.getByLabel('Customer preview link')).toHaveValue(/^https:\/\/www\.cjmmetals\.com\/preview\/[a-f0-9]{48}$/);
  const list=(await app.api('/api/customer-previews','GET',undefined,app.owner)).data;
  const p=list.find(x=>x.title==='Synthetic test gate'),token=p.url.split('/').at(-1);
  expect((await app.api(`/api/public/customer-previews/${token}/feedback`,'POST',{submissionId:crypto.randomUUID(),optionId:p.options[0].id,message:'Please enlarge the lettering.'},undefined,{'X-Lead-Key':'test-intake-key'})).status).toBe(201);
  await dialog.getByRole('button',{name:'Close',exact:true}).click();
  await page.reload();
  const card=page.getByRole('article').filter({hasText:'Synthetic test gate'});
  await expect(card).toContainText('1 customer comment');
  await card.getByRole('button',{name:'Manage',exact:true}).click();
  await expect(dialog.getByText('Please enlarge the lettering.')).toBeVisible();
  await dialog.getByRole('button',{name:'Disable link',exact:true}).click();
  expect((await app.api(`/api/public/customer-previews/${token}`,'GET',undefined,undefined,{'X-Lead-Key':'test-intake-key'})).status).toBe(404);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.screenshot({path:'test-results/customer-previews-suite.png',fullPage:true});
  expect(errors).toEqual([]);
});
