import {test,expect} from '@playwright/test';
import {testApp} from '../scripts/test-app.mjs';
let app;
test.beforeAll(async()=>{app=await testApp({serve:true});app.sqlite.prepare("UPDATE users SET credential_type='password' WHERE role='owner'").run();});
test.afterAll(async()=>app.close());
test('Engineering studio opens the current model and selectable hardware and dimensioned parts',async({page})=>{
 await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
 await page.goto(app.base+'/#/design-studio');
 await expect(page.getByRole('heading',{name:'CJM Design Studio',exact:true})).toBeVisible();
 const before=app.sqlite.prepare('SELECT count(*) AS n FROM customer_previews').get().n;
 await page.getByRole('button',{name:'View parts',exact:true}).click();
 await expect(page.locator('[aria-label="Select parts in the 3D model"]')).toHaveAttribute('data-ready','true',{timeout:60000});
 const catalog=(await app.api('/api/design-studio/film-table/parts','GET',undefined,app.owner)).data;
 const plate=catalog.parts.find(p=>p.name==='Feed arm mounting plate');
 await page.getByRole('button',{name:'Find a part',exact:true}).click();
 await page.getByLabel('Search parts',{exact:true}).fill('Feed arm mounting plate');
 await page.getByRole('button',{name:/Feed arm mounting plate/}).first().click();
 await expect(page.locator('[aria-label="Select parts in the 3D model"]')).toHaveAttribute('data-selected-part',plate.id);
 if(await page.getByRole('button',{name:'Drawing & dimensions',exact:true}).isVisible())await page.getByRole('button',{name:'Drawing & dimensions',exact:true}).click();
 const detail=page.getByRole('article',{name:'Selected part'});
 await expect(detail.getByRole('heading',{name:'Feed arm mounting plate',exact:true})).toBeVisible();
 await expect(detail.getByRole('img',{name:/dimensioned front, top and side drawing/})).toBeVisible();
 await expect(detail).toContainText('7 7/8″');await expect(detail).toContainText('12.7 mm');
 await detail.getByRole('button',{name:'Enlarge drawing'}).click();
 await expect(detail.getByRole('button',{name:'Fit drawing'})).toBeVisible();
 if(await page.getByRole('button',{name:'3D part',exact:true}).isVisible())await page.getByRole('button',{name:'3D part',exact:true}).click();
 await page.getByRole('button',{name:'Hide this piece',exact:true}).click();
 await expect(page.getByRole('button',{name:'Show all (1 hidden)',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Show all (1 hidden)',exact:true}).click();
 await page.getByRole('button',{name:'Fullscreen',exact:true}).click();
 await expect(page.getByLabel('Film table design workspace')).toHaveAttribute('data-fullscreen','true');
 await page.getByRole('button',{name:'Exit fullscreen',exact:true}).click();
 await page.getByRole('button',{name:'Find a part',exact:true}).click();
 await page.getByLabel('Search parts',{exact:true}).fill('Purchased nylon guide wheel');
 await page.getByRole('button',{name:/Purchased nylon guide wheel/}).click();
 await expect(page.getByLabel('Select parts in the 3D model')).toHaveAttribute('data-selected-part',catalog.parts.find(p=>p.name==='Purchased nylon guide wheel').id);
 await page.getByRole('button',{name:'Back to all parts',exact:true}).click();
 await expect(page.locator('[aria-label="Select parts in the 3D model"]')).toHaveAttribute('data-selected-part','');
 await page.getByRole('button',{name:'View model',exact:true}).click();
 await expect(page.locator('[aria-label="Interactive table; drag to rotate and scroll to zoom"]')).toHaveAttribute('data-ready','true',{timeout:60000});
 await page.getByLabel('Table process step',{exact:true}).selectOption('tension');
 await page.getByRole('button',{name:'Play animation',exact:true}).click();
 await expect(page.getByRole('button',{name:'Pause animation',exact:true})).toBeVisible();
 await expect.poll(async()=>Number(await page.getByLabel('Table process time',{exact:true}).inputValue())).toBeGreaterThan(0);
 await page.getByRole('button',{name:'Pause animation',exact:true}).click();
 await page.getByLabel('Animation speed',{exact:true}).selectOption('2');
 await page.getByRole('button',{name:'Cut list',exact:true}).click();
 await page.getByRole('searchbox',{name:'Search cut list'}).fill('Feed arm mounting plate');
 await page.getByRole('button',{name:new RegExp('Feed arm mounting plate '+plate.id)}).click();
 await expect(page.getByLabel('Select parts in the 3D model')).toHaveAttribute('data-selected-part',plate.id);
 if(await page.getByRole('button',{name:'Drawing & dimensions',exact:true}).isVisible())await page.getByRole('button',{name:'Drawing & dimensions',exact:true}).click();
 await detail.getByRole('button',{name:'Holes & curves',exact:true}).click();
 await expect(detail.getByRole('img',{name:/hole centers and curve dimensions page/})).toBeVisible();
 await page.getByLabel('Dimension units',{exact:true}).selectOption('mm');
 await detail.getByRole('button',{name:'All dimensions',exact:true}).click();
 await expect(detail).toContainText('200 mm');
 await expect(detail).toContainText('Straight outline segments');
 const download=page.waitForEvent('download');
 await page.getByRole('button',{name:'Save offline field book',exact:true}).click();
 expect((await download).suggestedFilename()).toContain(catalog.revision);
 await expect(page.getByRole('status').filter({hasText:'Field book downloaded'})).toBeVisible();
 expect(app.sqlite.prepare('SELECT count(*) AS n FROM customer_previews').get().n).toBe(before);
});
