import {test,expect} from '@playwright/test';
import {testApp} from '../scripts/test-app.mjs';
import {documentFixture} from '../scripts/document-activity-fixture.mjs';
let app,fixture;
test.beforeAll(async()=>{app=await testApp({serve:true});app.sqlite.prepare("UPDATE users SET credential_type='password' WHERE role='owner'").run();fixture=await documentFixture(app);for(const d of fixture.docs)await app.api(`/api/public/document-activity/${d.kind}/${d.token}`,'POST',fixture.body(d),undefined,fixture.key);});
test.afterAll(async()=>app.close());
test('Quote and invoice reports show customer activity without changing their status',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
 await page.goto(app.base+'/#/crm/quotes');
 await page.getByRole('button',{name:'Saved',exact:true}).click();
 await page.getByRole('button',{name:'Customer activity',exact:true}).first().click();
 let dialog=page.getByRole('dialog').last();
 await expect(dialog.getByText('Document visits',{exact:true}).locator('..')).toContainText('1');
 await expect(dialog.getByText('Active viewing time',{exact:true}).locator('..')).toContainText('12s');
 await expect(dialog.getByText('Recorded status:')).toContainText('sent');
 await expect(dialog.getByText('Existing opened counter:')).toContainText('7');
 await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await page.goto(app.base+`/#/finance/invoices?invoice=${fixture.docs[1].id}`);
 await page.getByRole('button',{name:'Customer activity',exact:true}).click();
 dialog=page.getByRole('dialog').last();
 await expect(dialog.getByText(/^Pay clicks/)).toContainText('1');
 await expect(dialog.getByText('Total recorded paid:')).toContainText('$0.00');
 await expect(dialog.getByText('No payments recorded.')).toBeVisible();
 await dialog.locator('summary').click();
 await expect(dialog.getByText('Read: 90%')).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.screenshot({path:'test-results/document-activity.png',fullPage:true});
 await page.keyboard.press('Escape');
 await expect(page.getByRole('dialog')).toHaveCount(1);
 expect(errors).toEqual([]);
});
