import {test,expect} from '@playwright/test';
import {testApp} from '../scripts/test-app.mjs';
let app,job,invoice;
test.beforeAll(async()=>{
 app=await testApp({serve:true});app.sqlite.prepare("UPDATE users SET credential_type='password',totp_secret='SYNTHETIC-ONLY' WHERE role='owner'").run();
 const create=async(url,body)=>{const r=await app.api(url,'POST',body,app.owner);expect(r.status).toBeLessThan(300);return r.data;};
 job=await create('/api/projects',{jobNumber:'INSIGHT-BROWSER',name:'Graph test job'});
 invoice=await create('/api/finance/invoices',{projectId:job.id,items:JSON.stringify([{description:'Graph work',qty:1,unitPriceCents:25000}])});
 app.sqlite.prepare("UPDATE fin_invoices SET status='sent',due_date=date('now','-10 days') WHERE id=?").run(invoice.id);
 await create('/api/crm/leads',{name:'Metals browser lead',site:'metals',source:'website',stage:'new'});
 await create('/api/crm/leads',{name:'Concrete browser lead',site:'concrete',source:'other',stage:'contacted'});
});
test.afterAll(async()=>app.close());
test.beforeEach(async({page})=>{await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);});
test('Graphs open matching records, then the exact invoice; mobile layout and filters',async({page},info)=>{
 await page.goto(app.base+'/#/finance/invoices');
 const graph=page.getByRole('region',{name:'Money to collect',exact:true});
 await expect(graph).toBeVisible();
 await page.getByRole('combobox',{name:'Business',exact:true}).selectOption('concrete');
 await expect(graph.getByText('No matching records for these filters.',{exact:true})).toBeVisible();
 await page.getByRole('combobox',{name:'Business',exact:true}).selectOption('metals');
 await graph.getByRole('button',{name:'1–30 days overdue: $250. View records',exact:true}).click();
 await expect(page.getByRole('heading',{name:'1–30 days overdue',exact:true})).toBeVisible();
 await page.getByRole('link',{name:new RegExp(invoice.number)}).click();
 await expect(page.getByRole('heading',{name:invoice.number,exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Close',exact:true}).click();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.screenshot({path:info.outputPath('invoice-insights-mobile.jpg'),fullPage:true});
 await page.setViewportSize({width:1440,height:1000});
 await page.screenshot({path:info.outputPath('invoice-insights-desktop.jpg'),fullPage:true});
});
test('Shared date selection, comparisons, expand/collapse, and Sales business scope',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});
 await page.goto(app.base+'/#/crm');
 await page.getByLabel('Insights from',{exact:true}).fill('2026-10-01');
 await page.getByLabel('Insights to',{exact:true}).fill('2026-10-10');
 await page.getByRole('checkbox',{name:'Compare previous period',exact:true}).check();
 await expect(page.getByText(/Previous: 2026-09-21/)).toBeVisible();
 await page.getByRole('button',{name:'More graphs (2)',exact:true}).click();
 await page.getByRole('combobox',{name:'Business',exact:true}).selectOption('concrete');
 const stages=page.getByRole('region',{name:'Leads by current stage',exact:true});
 await expect(stages.getByRole('button',{name:'contacted: 1. View records',exact:true})).toBeVisible();
 await expect(stages.getByRole('button',{name:'new: 1. View records',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Hide graphs',exact:true}).click();
 await expect(page.getByLabel('Insights from',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Show graphs',exact:true}).click();
 await page.getByRole('button',{name:'Money',exact:true}).click();
 await page.getByRole('link',{name:'Reports',exact:true}).filter({visible:true}).click();
 await expect(page.getByLabel('Insights from',{exact:true})).toHaveValue('2026-10-01');
 await expect(page.getByRole('checkbox',{name:'Compare previous period',exact:true})).toBeChecked();
 await page.getByLabel('Insights to',{exact:true}).fill('2026-09-01');
 await expect(page.getByRole('alert').filter({hasText:'Choose valid dates'})).toBeVisible();
});
test('Job costs link to that job’s expenses and invoices',async({page})=>{
 await page.goto(app.base+'/#/project/'+job.id+'?tab=money');
 await page.getByRole('link',{name:/Direct expenses/}).click();
 await expect(page.getByRole('heading',{name:'Expenses',exact:true})).toBeVisible();
 await expect(page).toHaveURL(new RegExp('projectId='+job.id));
 await page.goto(app.base+'/#/project/'+job.id+'?tab=money');
 await page.getByRole('link',{name:/Billed to date/}).click();
 await expect(page.getByText('Invoices for job #'+job.id,{exact:false})).toBeVisible();
 await expect(page.getByText(invoice.number,{exact:true})).toBeVisible();
});
