import {test,expect} from '@playwright/test';
import {testApp} from '../scripts/test-app.mjs';
let app;
test.beforeAll(async()=>{app=await testApp({serve:true});app.sqlite.prepare("UPDATE users SET credential_type='password' WHERE role='owner'").run();});
test.afterAll(async()=>app.close());
test('Create and edit an invoice with selected payment methods and reusable wire details',async({page})=>{
 await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
 await page.goto(app.base+'/#/finance/invoices');
 await page.getByRole('button',{name:'New invoice',exact:true}).first().click();
 await page.getByRole('button',{name:'No client record? Enter a name'}).click();
 await page.getByPlaceholder('Free-text name').fill('Payment test customer');
 await page.getByPlaceholder('Description',{exact:true}).fill('Synthetic fabrication');
 await page.locator('input[placeholder="0.00"]').first().fill('100');
 await page.getByRole('checkbox',{name:/Wire — bank transfer/}).check();
 await page.getByRole('checkbox',{name:/Stripe — pay online/}).uncheck();
 for(const [label,value] of [['Account holder name','Synthetic Company'],['Bank name','Synthetic Bank'],['Wire routing number','111000025'],['Account number','000012345678']])await page.getByLabel(label,{exact:true}).fill(value);
 await page.getByRole('button',{name:'Save wire details for future invoices'}).click();
 await expect(page.getByText('Wire details saved for future invoices',{exact:true})).toBeVisible();
 await page.getByRole('group',{name:'Payment options'}).screenshot({path:'test-results/invoice-payment-options-mobile.png'});
 await page.getByRole('button',{name:'Create invoice',exact:true}).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 let rows=(await app.api('/api/finance/invoices','GET',undefined,app.owner)).data;
 const row=rows.find(r=>r.clientName==='Payment test customer');
 expect(row.status).toBe('draft');
 expect(JSON.parse(row.paymentOptions)).toMatchObject({stripe:false,wire:true,wireDetails:{account:'000012345678'}});
 await page.getByRole('row').filter({hasText:row.number}).click();
 await page.getByRole('button',{name:'Edit',exact:true}).click();
 await expect(page.getByRole('checkbox',{name:/Wire — bank transfer/})).toBeChecked();
 await expect(page.getByRole('checkbox',{name:/Stripe — pay online/})).not.toBeChecked();
 await expect(page.getByLabel('Account number',{exact:true})).toHaveValue('000012345678');
 await page.getByRole('checkbox',{name:/Stripe — pay online/}).check();
 await page.getByRole('button',{name:'Save changes',exact:true}).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 rows=(await app.api('/api/finance/invoices','GET',undefined,app.owner)).data;
 expect(JSON.parse(rows.find(r=>r.id===row.id).paymentOptions)).toMatchObject({stripe:true,wire:true});
 await page.getByRole('button',{name:'New invoice',exact:true}).first().click();
 await page.getByRole('checkbox',{name:/Wire — bank transfer/}).check();
 await expect(page.getByLabel('Account number',{exact:true})).toHaveValue('000012345678');
 await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('group',{name:'Payment options'}).screenshot({path:'test-results/invoice-payment-options-desktop.png'});
});
