import {test,expect} from '@playwright/test';
import {testApp} from '../scripts/test-app.mjs';
let app;
test.beforeAll(async()=>{app=await testApp({serve:true});app.sqlite.prepare("UPDATE users SET credential_type='password' WHERE role='owner'").run();});
test.afterAll(async()=>app.close());
test('Plant preview has staggered film, tape, inspect/hide and animation without loading old geometry',async({page},testInfo)=>{
 test.setTimeout(120000);const errors=[],oldRequests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/design-studio/film-table/'))oldRequests.push(r.url());});
 await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
 await page.goto(app.base+'/#/design-studio/film-table');
 await expect(page.getByLabel('Table layout',{exact:true})).toHaveValue('plant');
 const canvas=page.getByLabel('Interactive plant model',{exact:true});await expect(canvas).toHaveAttribute('data-ready','true');
 await expect(page.getByLabel('Plant film setup')).toContainText('5 tape seams');
 await expect(page.getByRole('button',{name:'Cut list',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Film & tape rack',exact:true}).click();
 await canvas.screenshot({path:testInfo.outputPath('plant-rack-mobile.png')});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
 await page.getByRole('button',{name:'View parts',exact:true}).click();
 await page.getByLabel('Choose plant part',{exact:true}).selectOption('tape-roll-2');
 await expect(canvas).toHaveAttribute('data-selected-part','tape-roll-2');
 await expect(page.getByLabel('Selected plant part')).toContainText('Tape on the third PVC pipe');
 await page.getByRole('button',{name:'Hide this part',exact:true}).click();await expect(canvas).toHaveAttribute('data-hidden-count','1');
 await page.getByRole('button',{name:'Show all (1 hidden)',exact:true}).click();await expect(canvas).toHaveAttribute('data-hidden-count','0');
 await page.getByLabel('Choose plant part',{exact:true}).selectOption('caster-2.83--1');
 await expect(page.getByLabel('Selected plant part')).toContainText('Field measurements are needed');
 await page.getByRole('button',{name:'Fullscreen',exact:true}).click();await expect(page.getByLabel('Film table design workspace')).toHaveAttribute('data-fullscreen','true');
 await page.getByRole('button',{name:'Exit fullscreen',exact:true}).click();
 await page.getByRole('button',{name:'View model',exact:true}).click();
 await page.getByLabel('Plant process step',{exact:true}).selectOption('draw');
 await page.getByRole('button',{name:'Play animation',exact:true}).click();
 await expect.poll(async()=>Number(await page.getByLabel('Plant process time',{exact:true}).inputValue())).toBeGreaterThan(9);
 await page.getByRole('button',{name:'Pause animation',exact:true}).click();
 await page.getByLabel('Plant process step',{exact:true}).selectOption('hold');
 await page.setViewportSize({width:1440,height:1100});
 await page.getByRole('button',{name:'Whole setup',exact:true}).click();await canvas.screenshot({path:testInfo.outputPath('plant-overall-desktop.png')});
 await page.getByRole('button',{name:'Film & tape rack',exact:true}).click();await canvas.screenshot({path:testInfo.outputPath('plant-rack-desktop.png')});
 await page.getByRole('button',{name:'Wheeled bar',exact:true}).click();await canvas.screenshot({path:testInfo.outputPath('plant-bar-desktop.png')});
 await page.getByRole('button',{name:'View parts',exact:true}).click();
 await canvas.click({position:{x:Math.round((await canvas.boundingBox()).width*.46),y:250}});
 await expect(canvas).not.toHaveAttribute('data-selected-part','');
 await page.getByRole('button',{name:'Back to all parts',exact:true}).click();
 await page.getByRole('button',{name:'View model',exact:true}).click();
 await page.getByRole('button',{name:'Pipe supports',exact:true}).click();await canvas.screenshot({path:testInfo.outputPath('plant-supports-desktop.png')});
 expect(errors).toEqual([]);expect(oldRequests).toEqual([]);
});
