import {test,expect} from '@playwright/test';
import {testApp} from '../scripts/test-app.mjs';
let app;
test.beforeAll(async()=>{app=await testApp({serve:true});app.sqlite.prepare("UPDATE users SET credential_type='password',totp_secret='SYNTHETIC-ONLY' WHERE role='owner'").run();});
test.afterAll(async()=>app.close());
test('Owner can draft, review, publish and unpublish a complete bilingual project',async({page})=>{
 await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(app.base+'/#/marketing');
 await page.getByRole('button',{name:'Portfolio',exact:true}).click();
 await page.getByRole('button',{name:'Add work',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await dialog.getByLabel('Website',{exact:true}).selectOption('concrete');
 await dialog.getByLabel('Public project title').fill('Synthetic patio example');
 await dialog.getByLabel('City',{exact:true}).fill('Arlington');
 await dialog.getByLabel('Service',{exact:true}).selectOption('concrete-patios');
 await dialog.getByLabel('Photo shows').selectOption('completed');
 await dialog.getByLabel('What did CJM do?').fill('Synthetic test project scope');
 await dialog.getByLabel('Materials, finish and useful dimensions').fill('Synthetic materials for isolated testing');
 await dialog.getByText('Spanish title and description (optional)',{exact:true}).click();
 await dialog.getByLabel('Título público').fill('Patio de prueba');
 await dialog.getByLabel('Trabajo realizado').fill('Detalles sintéticos para la prueba');
 await dialog.getByLabel('Upload a photo').setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});
 await expect(dialog.getByRole('region',{name:'Public preview'}).locator('img')).toBeVisible();
 await dialog.getByLabel('Create a project page',{exact:false}).check();
 await expect(dialog.getByRole('button',{name:'Publish approved work'})).toBeDisabled();
 await dialog.getByRole('button',{name:'Save draft',exact:true}).click();
 await expect(dialog).toBeHidden();
 expect((await app.api('/api/public/portfolio?site=concrete')).data.items).toHaveLength(0);
 await page.getByRole('button',{name:'Edit',exact:true}).click();
 await dialog.getByLabel('I have approval',{exact:false}).check();
 await dialog.getByLabel('City',{exact:true}).fill('Mansfield');
 await expect(dialog.getByRole('button',{name:'Publish approved work'})).toBeDisabled();
 await dialog.getByLabel('I have approval',{exact:false}).check();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.screenshot({path:'test-results/public-work-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});
 await page.screenshot({path:'test-results/public-work-desktop.png',fullPage:true});
 await dialog.getByRole('button',{name:'Publish approved work'}).click();
 await expect(dialog).toBeHidden();
 const feed=(await app.api('/api/public/portfolio?site=concrete')).data.items;
 expect(feed).toHaveLength(1);expect(feed[0]).toMatchObject({titleEs:'Patio de prueba',city:'Mansfield',projectPage:true});
 await page.getByRole('button',{name:'Unpublish',exact:true}).click();
 await expect(page.getByRole('button',{name:'Review and publish',exact:true})).toBeVisible();
 expect((await app.api('/api/public/portfolio?site=concrete')).data.items).toHaveLength(0);
 expect(errors).toEqual([]);
});
