import {test,expect} from '@playwright/test';
import {testApp} from '../scripts/test-app.mjs';
let app;
test.beforeAll(async()=>{test.setTimeout(180000);app=await testApp({serve:true});app.sqlite.prepare("UPDATE users SET credential_type='password' WHERE role='owner'").run();});
test.afterAll(async()=>app?.close());
test('Customer PO: mobile entry, linked quote, documents, review, PDF and revision',async({page})=>{
  test.setTimeout(120000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
  await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
  const q=await app.api('/api/quotes','POST',{type:'custom',customerName:'Fixture Millwork',totalCents:1550000,payload:{type:'custom',customer:{name:'Buyer test',company:'Fixture Millwork'},notes:'Fabricate metal shelving and deliver.',depositPct:55,state:{color:'#E8E6E0'}}},app.owner);
  expect(q.status).toBe(201);
  await page.goto(app.base+'/#/finance/purchase-orders');
  await page.getByRole('button',{name:'New customer PO',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByLabel('Related quote',{exact:true}).selectOption(String(q.data.id));
  await dialog.getByRole('button',{name:'Fill customer, scope and price from quote'}).click();
  await expect(dialog.getByLabel('Customer / company')).toHaveValue('Fixture Millwork');
  await dialog.getByLabel('Customer project number',{exact:true}).fill('DEMO-578');
  await dialog.getByLabel('Finish / paint responsibilities').fill('Customer supplies bronze paint; CJM prepares and paints.');
  await dialog.getByLabel('Customer-supplied materials',{exact:true}).fill('Bronze paint');
  await dialog.getByLabel('Delivery included in price',{exact:true}).check();
  await dialog.getByLabel('Exclusions',{exact:true}).fill('Installation, shelf inserts and electrical.');
  await dialog.getByRole('button',{name:'Save draft PO',exact:true}).click();
  await expect(dialog.getByRole('heading',{level:2})).toHaveText(/CPO-.*Revision 1/);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await dialog.getByRole('button',{name:'Review',exact:true}).click();
  await expect(dialog.getByText('Quote comparison',{exact:true})).toBeVisible();
  await expect(dialog.getByText('Finish',{exact:true})).toBeVisible();
  await dialog.getByRole('button',{name:'Mark needs review'}).click();
  await expect(dialog.getByText('Needs review',{exact:true})).toBeVisible();
  await dialog.getByRole('button',{name:'Order',exact:true}).click();
  await dialog.getByLabel('Customer PO number (leave blank if pending)').fill('CM-TEST-578');
  await dialog.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(dialog.getByText('Save your changes before reviewing, uploading documents or exporting.')).toHaveCount(0);
  await dialog.getByRole('button',{name:'Documents',exact:true}).click();
  await dialog.getByLabel('Upload document (PDF, Word or image; 10 MB maximum)').setInputFiles({name:'original-po.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n%%EOF')});
  await expect(dialog.getByRole('button',{name:'original-po.pdf',exact:true})).toBeVisible();
  await dialog.getByRole('button',{name:'Review',exact:true}).click();
  await dialog.getByRole('checkbox').check();
  await dialog.getByLabel('Review / revision reason or sent-to details').fill('Buyer confirmed bronze paint instead of white. Delivery and painting included.');
  await dialog.getByRole('button',{name:'Confirm customer PO',exact:true}).click();
  await expect(dialog.getByText('Confirmed',{exact:true})).toBeVisible();
  await page.screenshot({path:'test-results/po-review-mobile.png',fullPage:true});
  const download=page.waitForEvent('download');
  await dialog.getByRole('button',{name:'Export PDF',exact:true}).click();
  await (await download).saveAs('test-results/customer-po.pdf');
  await dialog.getByLabel('Review / revision reason or sent-to details').fill('Adjust loading instructions.');
  await dialog.getByRole('button',{name:'Create revision',exact:true}).click();
  await expect(dialog.getByRole('heading',{level:2})).toHaveText(/Revision 2/);
  await dialog.getByRole('button',{name:'History',exact:true}).click();
  await expect(dialog.getByText('revision snapshot',{exact:true})).toBeVisible();
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'test-results/po-history-desktop.png',fullPage:true});
  await dialog.getByRole('button',{name:'Order',exact:true}).click();
  await page.screenshot({path:'test-results/po-form-desktop.png',fullPage:true});
  await dialog.getByLabel('Delivery instructions / terms').fill('Call before delivery.');
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:/^CPO-/,exact:false}).click();
  await expect(dialog.getByText('Recovered your unfinished draft.',{exact:false})).toBeVisible();
  await expect(dialog.getByLabel('Delivery instructions / terms')).toHaveValue('Call before delivery.');
  expect(errors).toEqual([]);
});
