import {test,expect} from '@playwright/test';
import {testApp} from '../scripts/test-app.mjs';
let app;
test.beforeAll(async()=>{app=await testApp({serve:true});app.sqlite.prepare("UPDATE users SET credential_type='password' WHERE role='owner'").run();});
test.afterAll(async()=>app.close());
test('Walnut dimensions follow part and top selection without changing customer previews',async({page})=>{
  const before=(await app.api('/api/customer-previews','GET',undefined,app.owner)).data;
  await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
  await page.goto(app.base+'/#/crm/previews?workspace=walnut');
  const workspace=page.getByRole('region',{name:'Walnut table parts and dimensions'});
  await expect(workspace.getByText('53 modeled components',{exact:true})).toBeVisible();
  await workspace.getByLabel('Search walnut parts').fill('angled leg');
  const legs=workspace.locator('.wt-list button');await expect(legs).toHaveCount(4);await legs.first().click();
  const detail=workspace.getByRole('article',{name:'Walnut selected part'});
  await expect(detail).toContainText('15° from vertical');
  await workspace.getByLabel('Walnut dimension units').selectOption('inch');
  await expect(detail).toContainText('21.875″');
  await workspace.getByLabel('Walnut top thickness').selectOption('2');
  await expect(detail).toContainText('22.875″');
  await workspace.getByLabel('Isolate selected part').check();
  await workspace.getByLabel('Walnut dimension units').selectOption('mm');
  await expect(detail).toContainText('581.03 mm');
  await workspace.getByRole('button',{name:'Overall dimensions',exact:true}).click();
  await expect(workspace.locator('.wt-overall')).toContainText('355.6 mm');
  await workspace.getByRole('button',{name:'Parts schedule',exact:true}).click();
  await expect(workspace.locator('.wt-body > .wt-table-scroll tbody tr')).toHaveCount(53);
  const download=page.waitForEvent('download');await workspace.getByRole('button',{name:'Download parts CSV'}).click();
  expect((await download).suggestedFilename()).toMatch(/^walnut-parts-2in-top-/);
  await page.emulateMedia({media:'print'});
  await expect(workspace.locator('.wt-print')).toBeVisible();
  await expect(workspace.locator('.wt-print')).toContainText('Foot sole closure');
  await page.emulateMedia({media:'screen'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  expect((await app.api('/api/customer-previews','GET',undefined,app.owner)).data).toEqual(before);
});
