import {test,expect} from '@playwright/test';
import {testApp} from '../scripts/test-app.mjs';
let app;
test.beforeAll(async()=>{app=await testApp({serve:true});app.sqlite.prepare("UPDATE users SET credential_type='password' WHERE role='owner'").run();});
test.afterAll(async()=>app.close());
test('Design Studio is a project chooser and opens only the selected workspace',async({page})=>{
  const modelRequests=[];
  page.on('request',request=>{if(request.url().includes('/api/design-studio/'))modelRequests.push(request.url());});
  await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
  await page.goto(app.base+'/#/design-studio');
  const gallery=page.getByRole('region',{name:'Design Studio projects'});
  await expect(gallery.getByRole('link')).toHaveCount(2);
  await expect(page.locator('canvas')).toHaveCount(0);
  expect(modelRequests).toHaveLength(0);
  await gallery.getByRole('link',{name:'Open Dallas table',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Dallas table',exact:true})).toBeVisible();
  await expect(page.getByLabel('Walnut parts 3D view')).toHaveAttribute('data-ready','true');
  expect(modelRequests.some(url=>url.includes('film-table'))).toBe(false);
  await expect(page.getByLabel('Film table design workspace')).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('heading',{name:'Dallas table',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'All projects',exact:true}).click();
  await expect(gallery).toBeVisible();
  await expect(page.locator('canvas')).toHaveCount(0);
  await page.screenshot({path:'test-results/design-studio-projects.png',fullPage:true});
  await gallery.getByRole('link',{name:'Open Film stretching table',exact:true}).click();
  await expect(page.getByLabel('Film table design workspace')).toBeVisible();
  await expect(page.getByLabel('Walnut table parts and dimensions')).toHaveCount(0);
  await page.goBack();
  await expect(gallery).toBeVisible();
  await page.goto(app.base+'/#/crm/previews');
  await expect(page.getByRole('heading',{name:'Customer previews',exact:true})).toBeVisible();
  await expect(page.getByLabel('Film table design workspace')).toHaveCount(0);
  await expect(page.getByLabel('Walnut table parts and dimensions')).toHaveCount(0);
});
test('Walnut dimensions follow part and top selection without changing customer previews',async({page})=>{
  const before=(await app.api('/api/customer-previews','GET',undefined,app.owner)).data;
  await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
  await page.goto(app.base+'/#/crm/previews?workspace=walnut');
  const workspace=page.getByRole('region',{name:'Walnut table parts and dimensions'});
  await expect(workspace.getByText('53 modeled components',{exact:true})).toBeVisible();
  await expect(page).toHaveURL(/#\/design-studio\/dallas-table$/);
  await workspace.getByRole('button',{name:'View parts',exact:true}).click();
  await workspace.getByRole('button',{name:'Find a part',exact:true}).click();
  await workspace.getByLabel('Search walnut parts').fill('angled leg');
  const legs=workspace.locator('.wt-list button');await expect(legs).toHaveCount(4);await legs.first().click();
  const detail=workspace.getByRole('article',{name:'Walnut selected part'});
  await expect(workspace.getByLabel('Walnut parts 3D view')).toHaveAttribute('data-visible-parts','1');
  if(await workspace.getByRole('button',{name:'Drawing & dimensions',exact:true}).isVisible())await workspace.getByRole('button',{name:'Drawing & dimensions',exact:true}).click();
  await expect(detail).toContainText('15° from vertical');
  await workspace.getByLabel('Walnut dimension units').selectOption('inch');
  await expect(detail).toContainText('21.875″');
  await workspace.getByLabel('Walnut top thickness').selectOption('2');
  await expect(detail).toContainText('22.875″');
  await detail.getByRole('button',{name:'Enlarge drawing',exact:true}).click();
  await expect(detail.getByRole('button',{name:'Fit drawing',exact:true})).toBeVisible();
  await workspace.getByLabel('Walnut dimension units').selectOption('mm');
  await expect(detail).toContainText('581.03 mm');
  if(await workspace.getByRole('button',{name:'3D part',exact:true}).isVisible())await workspace.getByRole('button',{name:'3D part',exact:true}).click();
  await workspace.getByRole('button',{name:'Hide this piece',exact:true}).click();
  await expect(workspace.getByLabel('Walnut parts 3D view')).toHaveAttribute('data-visible-parts','51');
  await workspace.getByRole('button',{name:'Show all (1 hidden)',exact:true}).click();
  await expect(workspace.getByLabel('Walnut parts 3D view')).toHaveAttribute('data-visible-parts','52');
  await workspace.getByRole('button',{name:'Overall dimensions',exact:true}).click();
  await expect(workspace.locator('.wt-overall')).toContainText('355.6 mm');
  await workspace.getByRole('button',{name:'Parts schedule',exact:true}).click();
  await expect(workspace.locator('.wt-body > .wt-table-scroll tbody tr')).toHaveCount(53);
  const download=page.waitForEvent('download');await workspace.getByRole('button',{name:'Download parts CSV'}).click();
  expect((await download).suggestedFilename()).toMatch(/^walnut-parts-2in-top-/);
  await page.emulateMedia({media:'print'});
  // Inspect the printable output independently of the screen controls.
  const printed=page.locator('.wt-print');
  await expect(printed).toBeVisible();
  await expect(printed).toContainText('Foot sole closure');
  await expect(printed.locator('h2')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollHeight-document.querySelector('.wt-print').getBoundingClientRect().height)).toBeLessThan(50);
  await page.screenshot({path:'test-results/walnut-parts-print.png',fullPage:true});
  await page.emulateMedia({media:'screen'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  expect((await app.api('/api/customer-previews','GET',undefined,app.owner)).data).toEqual(before);
});
