import {test,expect} from '@playwright/test';
import {testApp} from '../scripts/test-app.mjs';
let app;
test.beforeAll(async()=>{app=await testApp({serve:true});app.sqlite.prepare("UPDATE users SET credential_type='password' WHERE role='owner'").run();});
test.afterAll(async()=>app.close());
test('Design Studio is a project chooser and opens only the selected workspace',async({page})=>{
  const modelRequests=[];
  page.on('request',request=>{if(request.url().includes('/api/design-studio/'))modelRequests.push(request.url());});
  await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
  await page.goto(app.base+'/#/design-studio');
  const gallery=page.getByRole('region',{name:'Design Studio projects'});
  await expect(gallery.getByRole('link')).toHaveCount(2);
  await expect(page.locator('canvas')).toHaveCount(0);
  expect(modelRequests).toHaveLength(0);
  await gallery.getByRole('link',{name:'Open Dallas table',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Dallas table',exact:true})).toBeVisible();
  await expect(page.getByLabel('Walnut parts 3D view')).toHaveAttribute('data-ready','true');
  expect(modelRequests.some(url=>url.includes('film-table'))).toBe(false);
  await expect(page.getByLabel('Film table design workspace')).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('heading',{name:'Dallas table',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Projects',exact:true}).click();
  await expect(gallery).toBeVisible();
  await expect(page.locator('canvas')).toHaveCount(0);
  await page.screenshot({path:'test-results/design-studio-projects.png',fullPage:true});
  await gallery.getByRole('link',{name:'Open Film stretching table',exact:true}).click();
  await expect(page.getByLabel('Film table design workspace')).toBeVisible();
  await expect(page.getByLabel('Walnut table parts and dimensions')).toHaveCount(0);
  await page.goBack();
  await expect(gallery).toBeVisible();
  await page.goto(app.base+'/#/crm/previews');
  await expect(page.getByRole('heading',{name:'Customer previews',exact:true})).toBeVisible();
  await expect(page.getByLabel('Film table design workspace')).toHaveCount(0);
  await expect(page.getByLabel('Walnut table parts and dimensions')).toHaveCount(0);
});
test('Dallas opens one model with a reviewed cutting checklist that survives reloads',async({page})=>{
  const before=(await app.api('/api/customer-previews','GET',undefined,app.owner)).data;
  await page.addInitScript(token=>localStorage.setItem('wpt-auth-token',token),app.owner);
  await page.goto(app.base+'/#/design-studio/dallas-table');
  await expect(page).toHaveURL(/#\/design-studio\/dallas-table$/);
  const workspace=page.getByRole('region',{name:'Walnut table parts and dimensions'});
  await expect(workspace.getByLabel('Cutting progress')).toHaveText('0 / 57 cut');
  await expect(workspace.getByLabel('Walnut parts 3D view')).toHaveAttribute('data-ready','true');
  await expect(workspace.locator('canvas')).toHaveCount(1);
  await expect(workspace.getByRole('button',{name:'View parts',exact:true})).toHaveCount(0);
  const find=workspace.getByLabel('Find cutting part');
  await find.fill('Angled leg');
  await workspace.getByRole('button',{name:'Work on Angled leg WT-004',exact:true}).click();
  await expect(workspace.getByLabel('Walnut parts 3D view')).toHaveAttribute('data-visible-parts','1');
  await expect(workspace.getByLabel('Shop cut size in inches')).toHaveValue('');
  await expect(workspace.getByRole('button',{name:'Confirm shop size',exact:true})).toBeDisabled();
  await workspace.locator('.wt-shop-drawing summary').click();
  await expect(workspace.locator('.wt-shop-drawing')).toContainText('15° from vertical');
  await workspace.getByRole('button',{name:'Shop settings',exact:true}).click();
  await workspace.getByLabel('Walnut dimension units').selectOption('inch');
  await expect(workspace.getByRole('img',{name:'Dimensions on model',exact:true})).toContainText('21.875″');
  await workspace.getByLabel('Walnut top thickness').selectOption('2');
  await find.fill('Angled leg');
  await workspace.getByRole('button',{name:'Work on Angled leg WT-004',exact:true}).click();
  await workspace.getByRole('button',{name:'Shop settings',exact:true}).click();
  await workspace.getByLabel('Walnut dimension units').selectOption('mm');
  await expect(workspace.getByRole('img',{name:'Dimensions on model',exact:true})).toContainText('581.03 mm');
  await find.fill('Long upper rail');
  await workspace.getByRole('button',{name:'Work on Long upper rail WT-018',exact:true}).click();
  await expect(workspace.getByLabel('Shop cut size in inches')).toHaveValue('96');
  await expect(workspace.getByRole('button',{name:'Mark 1 cut',exact:true})).toHaveCount(0);
  await workspace.getByRole('button',{name:'Confirm shop size',exact:true}).click();
  await workspace.getByRole('button',{name:'Mark 1 cut',exact:true}).click();
  await workspace.getByRole('button',{name:'Mark 1 cut',exact:true}).click();
  await expect(workspace.getByRole('button',{name:'Complete',exact:true})).toBeDisabled();
  await expect(workspace.getByRole('button',{name:'Edit shop size',exact:true})).toBeDisabled();
  await workspace.getByRole('button',{name:'Undo one cut piece',exact:true}).click();
  await page.reload();
  await expect(workspace.getByLabel('Cutting progress')).toHaveText('1 / 57 cut');
  await workspace.getByRole('button',{name:'Shop settings',exact:true}).click();
  await expect(workspace.getByLabel('Walnut top thickness')).toHaveValue('2');
  await workspace.getByLabel('Walnut top thickness').selectOption('3');
  await expect(workspace.getByLabel('Cutting progress')).toHaveText('0 / 57 cut');
  await workspace.getByRole('button',{name:'Shop settings',exact:true}).click();
  await workspace.getByLabel('Walnut top thickness').selectOption('2');
  await expect(workspace.getByLabel('Cutting progress')).toHaveText('1 / 57 cut');
  await workspace.getByRole('button',{name:'Shop settings',exact:true}).click();
  const download=page.waitForEvent('download');await workspace.getByRole('button',{name:'Download cutting CSV',exact:true}).click();
  expect((await download).suggestedFilename()).toMatch(/^dallas-cutting-2in-top-/);
  await page.emulateMedia({media:'print'});
  const printed=page.locator('.wt-print');
  await expect(printed).toBeVisible();await expect(printed).toContainText('Foot sole closure');
  await expect(printed).toContainText('NEEDS DETAIL');await expect(printed).toContainText('96');
  expect(await page.evaluate(()=>document.documentElement.scrollHeight-document.querySelector('.wt-print').getBoundingClientRect().height)).toBeLessThan(50);
  await page.screenshot({path:'test-results/dallas-cutting-print.png',fullPage:true});
  await page.emulateMedia({media:'screen'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  expect((await app.api('/api/customer-previews','GET',undefined,app.owner)).data).toEqual(before);
});
