import { useState } from 'react';
import { Link } from 'wouter';
import Header from '@/components/Header';
import { EmployeeCard, EmployeeError, duration, stamp, kindLabel, statusLabel, employeeButton, employeePrimary, employeeInput, useEmployeeQuery, useEmployeeMutation } from './employee';

function ShiftReview({shift:s}:{shift:any}) {
  const [note,setNote]=useState(''),[end,setEnd]=useState(''),save=useEmployeeMutation(`/api/employee/review/${s.id}`),close=useEmployeeMutation(`/api/employee/shifts/${s.id}/close`);
  return <EmployeeCard><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{s.name}</h2><p className="mt-1 text-sm text-muted-foreground">{stamp(s.started_at)}{s.ended_at&&` → ${stamp(s.ended_at)}`}</p></div><span className="rounded-full bg-muted px-3 py-1 text-xs">{statusLabel(s.status)}</span></div><p className="mt-4 text-2xl font-semibold">{duration(s.entries.reduce((sum:number,e:any)=>sum+e.duration_min,0))}<span className="ml-2 text-sm font-normal text-muted-foreground">recorded paid time</span></p>{s.origin!=='clock'&&<p className="mt-3 rounded-lg bg-amber-500/10 p-3 text-sm">{s.origin==='manual'?'Missed-time request':'Carried-over timer'}: {s.reason}</p>}{s.long&&<p className="mt-3 text-sm text-amber-700 dark:text-amber-300">Over 12 hours. Confirm the actual hours and add a review note.</p>}<div className="mt-4 space-y-3">{s.entries.map((e:any)=><div key={e.id} className="border-t border-border pt-3 text-sm"><p className="font-medium">{e.project_name||kindLabel(e.work_kind)}</p><p className="mt-1 text-muted-foreground">{stamp(e.started_at)} → {e.ended_at?stamp(e.ended_at):'Running'} · {kindLabel(e.work_kind)} · {duration(e.duration_min)} paid</p></div>)}</div><label className="mt-4 block text-sm">Review note {s.long?'(required)':'(required when returning hours)'}<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} className={employeeInput}/></label>{s.ended_at?<div className="mt-4 grid grid-cols-2 gap-3"><button disabled={save.isPending} className={employeeButton} onClick={()=>save.mutate({version:s.version,action:'return',note})}>Request changes</button><button disabled={save.isPending} className={employeePrimary} onClick={()=>save.mutate({version:s.version,action:'approve',note})}>Approve hours</button></div>:<details className="mt-4 rounded-xl border border-border p-4"><summary className="cursor-pointer text-sm font-medium">Employee forgot to clock out?</summary><p className="mt-2 text-sm text-muted-foreground">Confirm their actual finish time. This creates an audited correction and leaves the shift waiting for approval.</p><label className="mt-3 block text-sm">Actual finish time<input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)} className={employeeInput}/></label><button disabled={close.isPending||!end||note.trim().length<3} onClick={()=>close.mutate({version:s.version,endedAt:new Date(end).getTime(),reason:note})} className={employeeButton+' mt-3'}>Record finish time</button></details>}{(save.isError||close.isError)&&<p role="alert" className="mt-3 text-sm text-destructive">{save.error?.message||close.error?.message}</p>}</EmployeeCard>;
}
function CorrectionReview({request:r}:{request:any}) {
  const [note,setNote]=useState(''),save=useEmployeeMutation(`/api/employee/time-requests/${r.id}/decision`),before=JSON.parse(r.original);
  return <EmployeeCard><h2 className="font-semibold">{r.name} · Time correction</h2><p className="mt-3 text-sm">{r.project_name||kindLabel(before.work_kind)}</p><div className="mt-3 space-y-2 rounded-xl bg-muted/40 p-3 text-sm"><p>Recorded: {stamp(before.started_at)} → {stamp(before.ended_at)}</p><p>Requested: {stamp(r.started_at)} → {stamp(r.ended_at)}</p></div><p className="mt-3 whitespace-pre-wrap text-sm">Reason: {r.reason}</p><label className="mt-3 block text-sm">Decision note (required)<textarea value={note} onChange={e=>setNote(e.target.value)} className={employeeInput}/></label><div className="mt-3 grid grid-cols-2 gap-3"><button disabled={save.isPending||note.trim().length<3} className={employeeButton} onClick={()=>save.mutate({action:'deny',note})}>Decline correction</button><button disabled={save.isPending||note.trim().length<3} className={employeePrimary} onClick={()=>save.mutate({action:'approve',note})}>Accept correction</button></div><p className="mt-3 text-xs text-muted-foreground">Accepted changes remain in the audit history. Review and approve the corrected shift afterward.</p>{save.isError&&<p role="alert" className="mt-3 text-sm text-destructive">{save.error.message}</p>}</EmployeeCard>;
}
function TeamSetup({data}:{data:any}) {
  const [breakPaid,setBreakPaid]=useState(!!data.policy.break_paid),[mealPaid,setMealPaid]=useState(!!data.policy.meal_paid),save=useEmployeeMutation('/api/employee/clock-policy');
  return <div className="space-y-5"><EmployeeCard><h2 className="text-lg font-semibold">Connect every login to payroll</h2><p className="mt-2 text-sm text-muted-foreground">Each employee needs one login linked to one employee profile, plus a dated pay rate. Existing recorded hours attach automatically when the login is linked.</p><div className="mt-4 flex flex-wrap gap-3"><Link className={employeeButton} href="/users">Manage logins</Link><Link className={employeePrimary} href="/hr/employees">Link employee profiles</Link></div>{data.people.map((p:any)=><div key={p.id} className="mt-4 border-t pt-4"><p className="font-medium">{p.name}</p>{p.issues.length?p.issues.map((issue:string)=><p key={issue} className="mt-1 text-sm text-amber-700 dark:text-amber-300">{issue}</p>):<p className="mt-1 text-sm text-emerald-700 dark:text-emerald-300">Employee profile and current pay rate connected</p>}</div>)}</EmployeeCard><EmployeeCard><h2 className="text-lg font-semibold">Break and meal settings</h2><p className="mt-2 text-sm text-muted-foreground">Review your company’s paid-time settings. Changes apply to new breaks only; already recorded segments keep their original setting.</p><label className="mt-4 flex min-h-12 items-center gap-3"><input type="checkbox" checked={breakPaid} onChange={e=>setBreakPaid(e.target.checked)} className="h-5 w-5"/>Pay regular breaks</label><label className="flex min-h-12 items-center gap-3"><input type="checkbox" checked={mealPaid} onChange={e=>setMealPaid(e.target.checked)} className="h-5 w-5"/>Pay meal breaks</label><button disabled={save.isPending} onClick={()=>save.mutate({breakPaid,mealPaid})} className={employeePrimary+' mt-3'}>Save break settings</button>{save.isSuccess&&<p role="status" className="mt-3 text-sm">Break settings saved.</p>}{save.isError&&<p role="alert" className="mt-3 text-destructive">{save.error.message}</p>}</EmployeeCard></div>;
}
function Assignments({data}:{data:any}) {
  const [person,setPerson]=useState(''),[job,setJob]=useState(''),save=useEmployeeMutation('/api/employee/assignments');
  return <EmployeeCard><h2 className="text-lg font-semibold">Assign employee jobs</h2><p className="mt-2 text-sm text-muted-foreground">Assigned employees can see the job, contact, work plan, materials and team updates. Their task assignments also grant job access unless you explicitly remove it here.</p><form className="mt-4 space-y-4" onSubmit={e=>{e.preventDefault();save.mutate({userId:Number(person),projectId:Number(job),active:true});}}><label className="block text-sm">Employee<select required className={employeeInput} value={person} onChange={e=>setPerson(e.target.value)}><option value="">Choose employee</option>{data.people.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="block text-sm">Job<select required className={employeeInput} value={job} onChange={e=>setJob(e.target.value)}><option value="">Choose job</option>{data.jobs.map((j:any)=><option key={j.id} value={j.id}>{j.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><button type="button" disabled={save.isPending||!person||!job} className={employeeButton} onClick={()=>save.mutate({userId:Number(person),projectId:Number(job),active:false})}>Remove access</button><button disabled={save.isPending} className={employeePrimary}>Assign job</button></div></form>{save.isError&&<p role="alert" className="mt-3 text-destructive">{save.error.message}</p>}{save.isSuccess&&<p role="status" className="mt-3 text-sm">Assignment saved.</p>}<div className="mt-5 space-y-3">{data.assignments.filter((a:any)=>a.active).map((a:any)=><p key={`${a.user_id}-${a.project_id}`} className="border-t pt-3 text-sm">{data.people.find((p:any)=>p.id===a.user_id)?.name||`Employee ${a.user_id}`} → {data.jobs.find((j:any)=>j.id===a.project_id)?.name||`Job ${a.project_id}`}</p>)}</div></EmployeeCard>;
}
export default function EmployeeApprovals() {
  const q=useEmployeeQuery('review','/api/employee/review'),[tab,setTab]=useState('hours');
  return <div className="mx-auto max-w-4xl space-y-5"><Header title="Employee approvals" description="Review recorded work, connect payroll, and assign the crew."/><div className="flex flex-wrap gap-3"><Link className={employeeButton} href="/hr/payroll">Open payroll</Link><Link className={employeeButton} href="/hr/leave">Time-off requests</Link></div><div role="tablist" aria-label="Employee management" className="grid grid-cols-3 gap-2">{[['hours','Review hours'],['setup','Team setup'],['jobs','Assignments']].map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} className={tab===key?employeePrimary:employeeButton} onClick={()=>setTab(key)}>{label}</button>)}</div>{q.isError?<EmployeeError error={q.error} retry={()=>q.refetch()}/>:!q.data?<p role="status">Loading employee review…</p>:tab==='setup'?<TeamSetup data={q.data}/>:tab==='jobs'?<Assignments data={q.data}/>:<>{q.data.people.some((p:any)=>p.issues.length)&&<button className="w-full rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-left text-sm" onClick={()=>setTab('setup')}>Some employee accounts need payroll setup. Open Team setup to review.</button>}{q.data.requests.map((r:any)=><CorrectionReview key={r.id} request={r}/>)}{q.data.shifts.map((s:any)=><ShiftReview key={s.id} shift={s}/>)}{!q.data.requests.length&&!q.data.shifts.length&&<EmployeeCard><p className="font-semibold">All submitted hours have been reviewed.</p><p className="mt-2 text-sm text-muted-foreground">New shifts and correction requests will appear here.</p></EmployeeCard>}</>}</div>;
}

export function EmployeeReviewSummary() {const q=useEmployeeQuery('review','/api/employee/review');if(!q.data)return null;const pending=q.data.shifts.filter((s:any)=>s.ended_at).length+q.data.requests.length,setup=q.data.people.filter((p:any)=>p.issues.length).length;return <Link href="/employee-approvals" className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-card p-5"><div><p className="font-semibold">Employee hours & approvals</p><p className="mt-1 text-sm text-muted-foreground">{pending} awaiting review · {setup} accounts need setup</p></div><span className="text-sm underline">Review crew →</span></Link>;}
