import {VisitContext,VisitContextNote,type VisitContextData} from '@/components/VisitContext';
import { useQuery } from '@tanstack/react-query';
import Modal from '@/components/Modal';
import { apiRequest } from '@/lib/queryClient';
import { secondaryBtn } from '@/lib/ui-styles';

type Variant={id:string;label:string;version:number;views:number;activeMs:number;loads:number;loadMs:number;errors:number;gateOpens:number;gateCloses:number;drags:number;zooms:number};
type Visit=VisitContextData & {id:string;version:number;startedAt:number;lastAt:number;activeMs:number;device:string;browser:string;variants:Variant[];links:Record<string,number>;webglFailed:number;contextLost:number};
type Activity={summary:{visits:number;activeMs:number;firstVisit:number|null;lastVisit:number|null;webglFailed:number;contextLost:number;feedback:number;acceptances:number};variants:Variant[];links:{name:string;clicks:number}[];devices:{device:string;deviceName?:string;browser:string;visits:number}[];visits:Visit[]};
type Preview={id:number;title:string;version:number;feedback:{id:number;kind:string;optionLabel:string;designVersion:number|null;createdAt:number;message:string;emailStatus:string}[]};
const names:Record<string,string>={main:'CJM Metals',concrete:'CJM Concrete',insulation:'CJM Insulation',phone:'Phone',email:'Email'};
function time(ms:number){const s=Math.floor(ms/1000);return s<60?`${s}s`:s<3600?`${Math.floor(s/60)}m ${s%60}s`:`${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m`;}
const date=(value:number|null)=>value?new Date(value).toLocaleString():'No visits yet';
function VariantDetails({v}:{v:Variant}){return <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-xs text-muted-foreground sm:grid-cols-3"><span>Active time: {time(v.activeMs)}</span><span>Viewed: {v.views}</span><span>Gate opens / closes: {v.gateOpens} / {v.gateCloses}</span><span>Rotate / pan gestures: {v.drags}</span><span>Zoom gestures: {v.zooms}</span><span>Load failures: {v.errors}</span><span>Successful loads: {v.loads}</span><span>Average load: {v.loads?`${(v.loadMs/v.loads/1000).toFixed(1)}s`:'—'}</span></div>;}

export default function PreviewActivity({preview,onClose}:{preview:Preview;onClose:()=>void}){
  const query=useQuery<Activity>({queryKey:['preview-activity',preview.id],queryFn:async()=>(await apiRequest('GET',`/api/customer-previews/${preview.id}/activity`)).json(),refetchInterval:15000});
  const data=query.data;
  return <Modal open onClose={onClose} title={`Customer activity · ${preview.title}`} maxWidth="max-w-4xl">
    <div className="space-y-6" aria-label="Preview activity report">
      <div className="flex flex-wrap items-center justify-between gap-3"><p className="max-w-xl text-sm text-muted-foreground">Activity starts when tracking was enabled. Visits are page openings, not identified people. Your Suite’s Open preview button excludes your own checks.</p><button className={secondaryBtn} disabled={query.isFetching} onClick={()=>query.refetch()}>Refresh activity</button></div>
      {query.isError&&<p role="alert">Could not refresh activity. Please try again.</p>}
      {!data?query.isPending&&<p>Loading activity…</p>:<>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[['Preview visits',data.summary.visits],['Active viewing time',time(data.summary.activeMs)],['Average per visit',time(data.summary.visits?data.summary.activeMs/data.summary.visits:0)],['Feedback received',data.summary.feedback],['Design acceptances',data.summary.acceptances],['Loading / display issues',data.variants.reduce((n,v)=>n+v.errors,0)+data.summary.webglFailed+data.summary.contextLost]].map(([label,value])=><div key={label} className="rounded-lg border border-border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div>
        <p className="text-xs text-muted-foreground">First visit: {date(data.summary.firstVisit)}<br/>Latest activity: {date(data.summary.lastVisit)}<br/>Time pauses in hidden tabs and after 60 seconds without activity. Counts can be incomplete when tracking is blocked. Loading time includes cached variants.</p>
        <section className="space-y-3"><h3 className="font-semibold">Variant interest & interactions</h3>{data.variants.filter(v=>v.views||v.errors).map(v=><article key={`${v.version}:${v.id}`} className="space-y-2 rounded-lg border border-border p-3"><p className="text-sm font-medium">{v.label} <span className="text-xs text-muted-foreground">· Version {v.version}{v.version!==preview.version?' (earlier design)':''}</span></p><VariantDetails v={v}/></article>)}{!data.summary.visits&&<p className="text-sm text-muted-foreground">No recorded visits yet. Share the customer link to start collecting activity.</p>}</section>
        <section className="space-y-3"><h3 className="font-semibold">Other links</h3><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(names).map(([key,name])=><div key={key} className="rounded-lg border border-border p-3 text-sm">{name}<strong className="ml-2">{data.links.find(l=>l.name===key)?.clicks||0}</strong></div>)}</div><p className="text-xs text-muted-foreground">Phone and email counts record link clicks, not completed calls or sent messages.</p></section>
        <section className="space-y-3"><h3 className="font-semibold">Devices & location</h3><VisitContextNote/>{data.devices.map(d=><p key={`${d.deviceName||d.device}:${d.browser}`} className="text-sm">{d.deviceName||d.device} · {d.browser}: {d.visits} {d.visits===1?'visit':'visits'}</p>)}<p className="text-sm text-muted-foreground">3D unavailable: {data.summary.webglFailed} · Graphics interruptions: {data.summary.contextLost}</p></section>
        <section className="space-y-3"><h3 className="font-semibold">Visit timeline</h3><p className="text-xs text-muted-foreground">Latest 100 visits. Totals above include all recorded visits. Expand a visit for its details.</p>{data.visits.map(v=><details key={v.id} className="rounded-lg border border-border p-3"><summary className="cursor-pointer text-sm">{date(v.startedAt)} · {v.deviceName||v.device} / {v.browser} · {time(v.activeMs)} active</summary><div className="mt-3 space-y-3"><VisitContext visit={v}/><p className="text-xs text-muted-foreground">Version {v.version} · Last activity {date(v.lastAt)}</p>{v.variants.filter(o=>o.views||o.errors).map(o=><div key={o.id}><p className="mb-1 text-sm font-medium">{o.label}</p><VariantDetails v={o}/></div>)}<p className="text-xs">Links: {Object.entries(v.links).filter(([,n])=>n).map(([key,n])=>`${names[key]} (${n})`).join(', ')||'None'}</p>{!!(v.webglFailed+v.contextLost)&&<p className="text-xs">3D unavailable: {v.webglFailed} · Graphics interruptions: {v.contextLost}</p>}</div></details>)}</section>
        <section className="space-y-3"><h3 className="font-semibold">Feedback & acceptance history</h3><p className="text-xs text-muted-foreground">Confirmed customer responses, including those received before activity tracking. Latest 50 responses.</p>{preview.feedback.map(f=><article key={f.id} className="rounded-lg border border-border p-3 text-sm"><p className="font-medium">{f.kind==='approval'?'Design accepted for quoting':'Feedback received'} · {f.optionLabel}</p><p className="text-xs text-muted-foreground">{date(f.createdAt)}{f.designVersion?` · Version ${f.designVersion}`:''}</p><p className="mt-2 whitespace-pre-wrap break-words">{f.message}</p><p className="mt-2 text-xs text-muted-foreground">{f.emailStatus==='sent'?'Email notification sent':f.emailStatus==='queued'?'Email notification queued':f.emailStatus==='attention'?'Email notification delayed':'Email notification not requested'}</p></article>)}{!preview.feedback.length&&<p className="text-sm text-muted-foreground">No responses yet.</p>}</section>
      </>}
    </div>
  </Modal>;
}
