import {useDeferredValue,useMemo,useState} from 'react';
import {Download,Search,ArrowUpRight} from 'lucide-react';
import type {ShopCatalog,ShopPart} from './types';
import {dimension,exactMm} from './fractions';
import {useUnit} from './MeasurementContext';
import {cutCsv,downloadFile,fitNotes,stockName} from './manufacturing';
export default function CutList({catalog,onOpen}:{catalog:ShopCatalog;onOpen:(id:string)=>void}){
 const unit=useUnit(),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[scope,setScope]=useState('custom'),q=useDeferredValue(search.toLowerCase());
 const custom=useMemo(()=>catalog.parts.filter(p=>p.kind==='custom'),[catalog.parts]);
 const rows=useMemo(()=>catalog.parts.filter(p=>(scope==='all'||scope==='checks'?(scope!=='checks'||p.kind==='custom'&&fitNotes(p).length>0):p.kind===scope)&&(!category||p.category===category)&&[p.id,p.name,p.variant,p.stock].join(' ').toLowerCase().includes(q)),[catalog.parts,scope,category,q]);
 return <section className="fs-field-panel" aria-label="Cut list and field book">
  <div className="fs-metrics"><div><strong>{custom.length}</strong><span>Custom part drawings</span></div><div><strong>{custom.reduce((n,p)=>n+p.quantity,0)}</strong><span>Custom pieces in this model</span></div><div><strong>{custom.filter(p=>fitNotes(p).length).length}</strong><span>Drawings with fit checks</span></div><div><strong>1/16″</strong><span>Fraction display · exact values available</span></div></div>
  <div className="fs-actions"><h3 style={{fontSize:18,fontWeight:650,marginRight:'auto'}}>Cut list &amp; field book</h3><button onClick={()=>downloadFile(cutCsv(catalog.parts,catalog.revision),'film-table-cut-list-'+catalog.revision+'.csv','text/csv')}><Download size={16}/>Export cut list</button></div>
  <p className="fs-muted">Choose a part for its drawing, hole locations, curve dimensions and stock details. Quantities include every matching instance; variants keep different hole layouts separate.</p>
  <div className="fs-notice">Dimensions come from the model. Confirm material grade, tolerances and cutting allowance before manufacture. The finished envelope is not automatically a stock blank or a saw setting.</div>
  <div className="fs-filters"><input aria-label="Search cut list" type="search" placeholder="Search a part, stock or drawing number…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Cut list scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="custom">Custom / to manufacture</option><option value="checks">Fit checks needed</option><option value="purchased">Purchased hardware</option><option value="all">All components</option></select><select aria-label="Cut list category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{[...new Set(catalog.parts.map(p=>p.category))].map(c=><option key={c}>{c}</option>)}</select></div>
  <div className="fs-table-scroll" style={{maxHeight:'65vh'}}><table className="fs-cut-table"><caption>{rows.length} drawings · Revision {catalog.revision}</caption><thead><tr><th>Part / drawing</th><th>Qty</th><th>Stock</th><th>Finished X × Y × Z</th><th>Recorded cut length</th><th>Fit notes</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><button onClick={()=>onOpen(p.id)}><span>{p.name}<small>{p.id}{p.variant?' · '+p.variant:''}</small></span><ArrowUpRight size={14}/></button></td><td>{p.quantity}</td><td>{stockName(p)}</td><td>{p.dimensions.map(v=>dimension(v,unit)).join(' × ')}{unit!=='mm'&&<small>{p.dimensions.map(exactMm).join(' × ')}</small>}</td><td>{p.cutLengthMm?dimension(p.cutLengthMm,unit):'See finished dimensions'}{p.cutLengthMm&&<small>{exactMm(p.cutLengthMm)}</small>}</td><td><span className={'fs-status'+(fitNotes(p).length?' check':'')}>{fitNotes(p).length?'Check fit':'Model dimensions'}</span></td></tr>)}</tbody></table>{!rows.length&&<p className="fs-empty">No parts match these filters.</p>}</div>
 </section>;
}
