import {useState} from 'react';
import {flushSync} from 'react-dom';
import {Download,Printer,ClipboardCheck,Ruler} from 'lucide-react';
import type {ShopPart,Point} from './types';
import {dimension,exactMm} from './fractions';
import {useUnit} from './MeasurementContext';
import {dimensionLabels} from './dimension-labels';
import {partChecks,stockName,downloadFile} from './manufacturing';
import PartDrawing from './PartDrawing';
import {FeaturePage,featureCount} from './PartFeatureDrawing';

export default function PartSheet({part:p,revision}:{part:ShopPart;revision:string}){
 const unit=useUnit(),[tab,setTab]=useState('drawing'),[page,setPage]=useState(0),[zoom,setZoom]=useState(false),[points,setPoints]=useState(false),[printing,setPrinting]=useState(false);
 const fmt=(n:number)=>dimension(n,unit),coord=(v:Point)=>v.map(fmt).join(' / '),checks=partChecks(p),pages=Math.ceil(featureCount(p)/2);
 const measure=(v:number)=><><b>{fmt(v)}</b>{unit!=='mm'&&<small>{exactMm(v)}</small>}</>;
 const print=()=>{flushSync(()=>setPrinting(true));window.print();setPrinting(false);};
 const download=()=>{const svg=document.getElementById('shop-part-drawing');if(svg)downloadFile(new XMLSerializer().serializeToString(svg),p.id+'-'+revision+'.svg','image/svg+xml');};
 const dimensions=<div className="fs-tables">
  <h4>Stock &amp; finished size</h4><table><tbody><tr><th>Quantity</th><td>{p.quantity} pieces</td></tr><tr><th>Stock</th><td>{stockName(p)}</td></tr><tr><th>Material grade</th><td>{p.fabrication?.materialGrade||'Not specified'}</td></tr><tr><th>Finished envelope X / Y / Z</th><td>{coord(p.dimensions)}<small>{p.dimensions.map(exactMm).join(' / ')}</small></td></tr><tr><th>Stock cut length</th><td>{p.cutLengthMm?measure(p.cutLengthMm):'Not specified separately; use the finished dimensions and confirm the blank / cutting allowance.'}</td></tr>{p.fabrication?.stockWidthMm&&<tr><th>Stock width</th><td>{measure(p.fabrication.stockWidthMm)}</td></tr>}{p.fabrication?.construction&&<tr><th>Construction</th><td>{p.fabrication.construction}</td></tr>}{p.measurements?.map((m,i)=><tr key={i}><th>{m.label.replace('Extruded stock depth (before edge bevel)','Profile extrusion length / thickness')}</th><td>{measure(m.mm)}</td></tr>)}</tbody></table>
  <h4>Holes &amp; circular openings · {p.holes.length}</h4><p className="fs-muted">X / Y / Z are the drawing axes. Bore span is the modeled opening, not a tap-drill depth. Exact values are retained for fits.</p>{p.holes.length?<div className="fs-table-scroll"><table><thead><tr><th>Mark / type</th><th>Diameter</th><th>Center X / Y / Z</th><th>End X / Y / Z</th><th>Bore span</th></tr></thead><tbody>{p.holes.map((h,i)=><tr key={i}><th>H{i+1}<small>{h.kind}</small></th><td>{measure(h.diameter)}</td><td>{coord(h.start)}<small>{h.start.map(exactMm).join(' / ')}</small></td><td>{coord(h.end)}<small>{h.end.map(exactMm).join(' / ')}</small></td><td>{measure(Math.hypot(...h.end.map((v,j)=>v-h.start[j])))}</td></tr>)}</tbody></table></div>:<p>No circular openings recorded.</p>}
  {!!p.radii.length&&<><h4>Curves &amp; radii</h4><table><thead><tr><th>Mark</th><th>Radius</th><th>Center X / Y / Z</th></tr></thead><tbody>{p.radii.map((r,i)=><tr key={i}><th>R{i+1}</th><td>{measure(r.radius)}</td><td>{coord(r.center)}<small>{r.center.map(exactMm).join(' / ')}</small></td></tr>)}</tbody></table></>}
  {!!p.notches.length&&<><h4>Rectangular cutouts</h4><table><thead><tr><th>Cut</th><th>Start X / Y / Z</th><th>End X / Y / Z</th><th>Size X / Y / Z</th></tr></thead><tbody>{p.notches.map((n,i)=><tr key={i}><th>N{i+1}</th><td>{coord(n.min)}</td><td>{coord(n.max)}</td><td>{n.max.map((v,j)=>fmt(v-n.min[j])).join(' / ')}</td></tr>)}</tbody></table></>}
  {!!p.segments?.length&&<><h4>Straight outline segments</h4><p className="fs-muted">Length and angle follow the captured profile. Angles are measured in its drawing plane, not a saw setting.</p><div className="fs-table-scroll"><table><thead><tr><th>Edge</th><th>Start X / Y / Z</th><th>End X / Y / Z</th><th>Length</th><th>Angle / drawing plane</th></tr></thead><tbody>{p.segments.map((s,i)=>{const delta=s.end.map((v,j)=>v-s.start[j]),plane=s.normal?s.normal.map(Math.abs).indexOf(Math.max(...s.normal.map(Math.abs))):p.vertices.length?([0,1,2].sort((a,b)=>(Math.max(...p.vertices.map(v=>v[a]))-Math.min(...p.vertices.map(v=>v[a])))-(Math.max(...p.vertices.map(v=>v[b]))-Math.min(...p.vertices.map(v=>v[b]))))[0]):2;const [a,b]=plane===2?[0,1]:plane===1?[0,2]:[2,1];return <tr key={i}><th>E{i+1}</th><td>{coord(s.start)}</td><td>{coord(s.end)}</td><td>{measure(Math.hypot(...delta))}</td><td>{(Math.atan2(delta[b],delta[a])*180/Math.PI).toFixed(2)}°<small>{['X','Y','Z'][a]} / {['X','Y','Z'][b]}</small></td></tr>;})}</tbody></table></div></>}
  {!!p.vertices.length&&<><h4>Outline coordinates</h4><p className="fs-muted">P labels correspond to the outline drawing.</p><div className="fs-table-scroll"><table><thead><tr><th>Point</th><th>X</th><th>Y</th><th>Z</th></tr></thead><tbody>{p.vertices.map((v,i)=><tr key={i}><th>P{i+1}</th>{v.map((n,j)=><td key={j}>{measure(n)}</td>)}</tr>)}</tbody></table></div></>}
 </div>;
 return <article className="fs-sheet fs-print-root" aria-label="Selected part">
  <header className="fs-sheet-heading"><span className="fs-eyebrow">{p.id} · {p.category} · {p.quantity} {p.quantity===1?'piece':'pieces'}</span><h3>{p.name}</h3><p>{p.variant&&p.variant+' · '}{stockName(p)}</p><span className="fs-revision">REV {revision} · Model dimensions</span></header>
  <dl className="fs-dimensions">{dimensionLabels(p).map((label,i)=><div key={label}><dt>{label}</dt><dd>{fmt(p.dimensions[i])}</dd><small>{exactMm(p.dimensions[i])}</small></div>)}</dl>
  <div className="fs-actions fs-screen-only"><button onClick={print}><Printer size={16}/>Print part / save PDF</button><button onClick={download}><Download size={16}/>SVG overview</button></div>
  <nav className="fs-subtabs fs-screen-only" aria-label="Part details">{[['drawing','Drawing'],['features','Holes & curves'],['dimensions','All dimensions'],['checks','Before cutting']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}{key==='checks'&&checks.length>0&&<span>{checks.length}</span>}</button>)}</nav>
  <div className={tab==='drawing'?'':'fs-screen-hidden'}><div className="fs-actions fs-screen-only"><label><input type="checkbox" checked={points} onChange={e=>setPoints(e.target.checked)}/> Outline point labels</label><button onClick={()=>setZoom(v=>!v)}>{zoom?'Fit drawing':'Enlarge drawing'}</button></div><div className="fs-drawing-scroll"><div style={{minWidth:zoom?1100:undefined}}><PartDrawing part={p} points={points} unit={unit} features={false} revision={revision}/></div></div></div>
  {tab==='features'&&<div className="fs-screen-only">{pages?<><div className="fs-actions"><label>Detail page <select aria-label="Hole and curve detail page" value={page} onChange={e=>setPage(Number(e.target.value))}>{Array.from({length:pages},(_,i)=><option value={i} key={i}>{i+1} of {pages}</option>)}</select></label><button disabled={page===0} onClick={()=>setPage(v=>v-1)}>Previous</button><button disabled={page===pages-1} onClick={()=>setPage(v=>v+1)}>Next</button></div><div className="fs-drawing-scroll"><div style={{minWidth:650}}><FeaturePage part={p} page={page} unit={unit} revision={revision}/></div></div></>:<p className="fs-empty">No circular holes or radii recorded for this part. See the outline and all dimensions.</p>}</div>}
  {tab==='dimensions'&&<div className="fs-screen-only">{dimensions}</div>}
  {tab==='checks'&&<div className="fs-screen-only fs-checks"><h4><ClipboardCheck size={18}/> Before cutting</h4><p>Confirm the material grade, tolerances, cutting allowance and mating hardware. These drawings reflect the model; they are not released fabrication instructions.</p>{checks.length>0&&<ul>{checks.map((n,i)=><li key={i}>{n}</li>)}</ul>}<h4>Part notes</h4>{p.notes.length?<ul>{p.notes.map((n,i)=><li key={i}>{n}</li>)}</ul>:<p>No additional notes recorded.</p>}</div>}
  {printing&&<div className="fs-print-only">{Array.from({length:pages},(_,i)=><div className="fs-print-page" key={i}><FeaturePage part={p} page={i} unit={unit} revision={revision}/></div>)}{dimensions}<h4>Checks &amp; notes</h4><p>Material grade, tolerances, cutting allowance and mating fits require confirmation.</p><ul>{[...new Set([...checks,...p.notes])].map((n,i)=><li key={i}>{n}</li>)}</ul></div>}
  <footer className="fs-sheet-footer"><Ruler size={14}/>{unit==='fraction'?'Nearest 1/16″ · Exact values in All dimensions':'Exact model values'} · X / Y / Z from drawing datum</footer>
 </article>;
}
