import {useEffect,useMemo,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {secondaryBtn,inputCls} from '@/lib/ui-styles';
import {dimension,exactMm} from './fractions';
import {useUnit} from './MeasurementContext';
import {dimensionLabels} from './dimension-labels';
import {loadStudioModel} from './studio-model';
import {makePartIndex,isolatedPart} from './part-selection';

const views={overall:[[7.3,6,8.1],[-.28,.58,-.65]],supply:[[0,6.5,-6],[0,.6,-3.68]],mounts:[[3.55,.84,-3.28],[3.05,.744,-2.96]],pipe:[[3.48,1.08,-3.63],[3.015,.855,-3.34]],braces:[[3.72,.90,3.70],[2.99,.64,3.22]],drive:[[.30,1.18,3.92],[0,.948,3.505]]};
export default function PartExplorer({parts,revision,onSelect,hiddenParts,onHiddenChange,requestedPart}){
 const unit=useUnit(),inchFraction=n=>dimension(n,unit);
 const host=useRef(null),controls=useRef(null),notify=useRef(onSelect),hiddenRef=useRef(hiddenParts),notifyHidden=useRef(onHiddenChange);
 notify.current=onSelect;hiddenRef.current=hiddenParts;notifyHidden.current=onHiddenChange;
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[hover,setHover]=useState(''),[selected,setSelected]=useState(''),[instance,setInstance]=useState(''),[retry,setRetry]=useState(0),[finding,setFinding]=useState(false),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[kind,setKind]=useState('');
 const byId=useMemo(()=>new Map(parts.map(p=>[p.id,p])),[parts]),active=byId.get(selected),hoverPart=byId.get(hover);
 const filtered=useMemo(()=>parts.filter(p=>(!category||p.category===category)&&(!kind||p.kind===kind)&&[p.name,p.id,p.stock,p.variant].join(' ').toLowerCase().includes(search.toLowerCase())),[parts,category,kind,search]);
 useEffect(()=>{if(ready&&requestedPart)controls.current?.choose(requestedPart);},[ready,requestedPart]);
 useEffect(()=>{controls.current?.applyHidden();},[hiddenParts]);
 useEffect(()=>{
  let stopped=false,cleanup;setReady(false);setError('');setSelected('');notify.current('');
  (async()=>{
   const {model,lib}=await loadStudioModel(revision);if(stopped)return;
   const process=lib.createProcess(model);process.apply(lib.PROCESS_STEPS.find(s=>s.id==='cutFar').start);model.root.updateMatrixWorld(true);
   const scene=new T.Scene();scene.background=new T.Color('#edf0eb');scene.add(model.root);
   model.root.traverse(o=>{if(o.isMesh&&o.material.transparent)o.visible=false;});
   const index=makePartIndex(model.root),baseline=new Map(index.entries.map(e=>[e.mesh,e.mesh.visible]));
   const renderer=new T.WebGLRenderer({antialias:true});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;host.current.appendChild(renderer.domElement);
   const camera=new T.PerspectiveCamera(36,1,.001,100),orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.minDistance=.008;orbit.maxDistance=25;
   const env=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),lightmap=pmrem.fromScene(env,.03);scene.environment=lightmap.texture;env.dispose();pmrem.dispose();scene.add(new T.HemisphereLight('#eef5ff','#78877a',1.4));const sun=new T.DirectionalLight('#fff5df',2.4);sun.position.set(-3,7,4);scene.add(sun);
   const highlightMaterial=new T.MeshStandardMaterial({color:'#009eaa',emissive:'#006773',emissiveIntensity:.35,metalness:.25,roughness:.4,polygonOffset:true,polygonOffsetFactor:-2,polygonOffsetUnits:-2,side:T.DoubleSide}),isolationMaterial=new T.MeshStandardMaterial({color:'#a8b8bd',metalness:.5,roughness:.38,side:T.DoubleSide});
   let highlight=null,isolated=null,raf=0,hoverHit=null,down=null,pointer=null,chosen='',chosenInstance='',saved=null,dirty=false,lastPick=0,visible=true;
   const ray=new T.Raycaster();
   const request=()=>{if(!stopped&&!raf&&visible&&!document.hidden)raf=requestAnimationFrame(render);};
   const clearHover=()=>{if(highlight){scene.remove(highlight);highlight=null;}hoverHit=null;setHover('');host.current.dataset.hoverPart='';renderer.domElement.style.cursor='grab';};
   const hitTest=()=>{dirty=false;if(!pointer||chosen)return;const rect=renderer.domElement.getBoundingClientRect();camera.updateMatrixWorld();ray.setFromCamera(new T.Vector2((pointer.x-rect.left)/rect.width*2-1,-(pointer.y-rect.top)/rect.height*2+1),camera);const {hit,checked}=index.pick(ray);host.current.dataset.pickChecks=String(checked);if(hit?.instance===hoverHit?.instance)return;clearHover();if(!hit)return;hoverHit=hit;setHover(hit.id);host.current.dataset.hoverPart=hit.id;renderer.domElement.style.cursor='pointer';highlight=new T.Group();for(const original of index.instances.get(hit.instance)){const mesh=new T.Mesh(original.geometry,highlightMaterial);mesh.matrixAutoUpdate=false;mesh.matrix.copy(original.matrixWorld);highlight.add(mesh);}scene.add(highlight);};
   function render(now){raf=0;const moving=orbit.update();if(down||moving){dirty=!!pointer;if(highlight)clearHover();}else if(dirty&&now-lastPick>=70){lastPick=now;hitTest();}renderer.render(scene,camera);if(moving||(!down&&dirty))request();}
   const removeIsolation=()=>{if(!isolated)return;scene.remove(isolated);isolated.traverse(o=>o.geometry?.dispose());isolated=null;};
   const fit=front=>{if(!isolated)return;const box=new T.Box3().setFromObject(isolated),center=box.getCenter(new T.Vector3()),radius=box.getSize(new T.Vector3()).length()/2,distance=radius/Math.sin(T.MathUtils.degToRad(camera.fov/2))/Math.min(1,camera.aspect);orbit.target.copy(center);camera.position.copy(center).add((front?new T.Vector3(0,0,1):new T.Vector3(.5,.3,1).normalize()).multiplyScalar(distance*1.15));orbit.update();request();};
   const choose=(id,preferred)=>{const result=isolatedPart(index,id,preferred);if(!result)return;if(!chosen)saved={position:camera.position.clone(),target:orbit.target.clone()};clearHover();pointer=null;chosen=id;chosenInstance=result.instance;removeIsolation();model.root.visible=false;isolated=result.group;isolated.traverse(o=>{if(o.isMesh)o.material=isolationMaterial;});scene.add(isolated);fit(false);setSelected(id);setInstance(chosenInstance);setFinding(false);host.current.dataset.selectedPart=id;host.current.dataset.selectedInstance=chosenInstance;notify.current(id);request();};
   const applyHidden=()=>{const hidden=new Set(hiddenRef.current);for(const e of index.entries)e.mesh.visible=baseline.get(e.mesh)&&!hidden.has(e.instance);host.current.dataset.hiddenCount=String(hidden.size);clearHover();request();};
   const back=()=>{chosen='';chosenInstance='';removeIsolation();model.root.visible=true;setSelected('');setInstance('');notify.current('');host.current.dataset.selectedPart='';host.current.dataset.selectedInstance='';if(saved){camera.position.copy(saved.position);orbit.target.copy(saved.target);}orbit.update();applyHidden();};
   const hide=()=>{if(!chosenInstance)return;const hidden=new Set(hiddenRef.current);if(hidden.has(chosenInstance))hidden.delete(chosenInstance);else hidden.add(chosenInstance);const next=[...hidden];hiddenRef.current=next;notifyHidden.current(next);back();};
   const showAll=()=>{hiddenRef.current=[];notifyHidden.current([]);applyHidden();};
   const view=name=>{if(chosen)back();const [p,t]=views[name];camera.position.set(...p);orbit.target.set(...t);camera.position.sub(orbit.target).multiplyScalar(Math.max(1,(name==='overall'||name==='supply'?1.35:.9)/camera.aspect)).add(orbit.target);orbit.update();request();};
   const move=e=>{pointer={x:e.clientX,y:e.clientY};dirty=true;if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)down.drag=true;request();};
   const leave=()=>{pointer=null;dirty=false;clearHover();request();};
   const start=e=>{if(e.button===0)down={x:e.clientX,y:e.clientY,drag:false};clearHover();};
   const end=e=>{if(e.button===0&&down&&!down.drag&&!chosen){pointer={x:e.clientX,y:e.clientY};hitTest();if(hoverHit)choose(hoverHit.id,hoverHit.instance);}down=null;request();};
   const cancel=()=>{down=null;leave();};
   const lost=e=>{e.preventDefault();if(!stopped)setError('The 3D view paused. Reopen it below.');};
   const canvas=renderer.domElement;canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerleave',leave);canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',cancel);canvas.addEventListener('webglcontextlost',lost);
   const resize=new ResizeObserver(()=>{if(!host.current)return;const w=host.current.clientWidth,h=host.current.clientHeight;visible=w>0&&h>0;if(!visible){cancelAnimationFrame(raf);raf=0;return;}camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,1.25,Math.sqrt(900000/(w*h))));renderer.setSize(w,h);if(isolated)fit(false);request();});resize.observe(host.current);orbit.addEventListener('change',request);
   const visibility=()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;}else request();};document.addEventListener('visibilitychange',visibility);
   camera.aspect=host.current.clientWidth/host.current.clientHeight;camera.updateProjectionMatrix();view('overall');controls.current={choose,back,view,hide,showAll,applyHidden,fit};applyHidden();setReady(true);host.current.dataset.ready='true';
   cleanup=()=>{cancelAnimationFrame(raf);resize.disconnect();document.removeEventListener('visibilitychange',visibility);orbit.dispose();removeIsolation();const gs=new Set(),ms=new Set();model.root.traverse(o=>{if(o.geometry)gs.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:o.material?[o.material]:[])ms.add(m);});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());highlightMaterial.dispose();isolationMaterial.dispose();lightmap.dispose();renderer.dispose();renderer.forceContextLoss();canvas.remove();controls.current=null;};
  })().catch(e=>{if(!stopped)setError(e.message||'Could not open parts view.');});
  return()=>{stopped=true;cleanup?.();};
 },[retry,parts,revision]);
 return <section className="space-y-3" aria-label="Interactive parts explorer">
  <div className="flex flex-wrap gap-2">{selected&&<><button className={secondaryBtn} onClick={()=>controls.current?.back()}>Back to all parts</button><button className={secondaryBtn} onClick={()=>controls.current?.hide()}>{hiddenParts.includes(instance)?'Show this piece':'Hide this piece'}</button></>}<button className={secondaryBtn} aria-expanded={finding} onClick={()=>setFinding(v=>!v)}>Find a part</button>{hiddenParts.length>0&&<button className={secondaryBtn} onClick={()=>controls.current?.showAll()}>Show all ({hiddenParts.length} hidden)</button>}</div>
  {finding&&<div className="space-y-2 rounded-lg border border-border p-3" aria-label="Find parts"><input type="search" aria-label="Search parts" placeholder="Search plates, wheels, pins…" className={inputCls} value={search} onChange={e=>setSearch(e.target.value)}/><div className="flex gap-2"><select className={inputCls} aria-label="Part category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{[...new Set(parts.map(p=>p.category))].map(c=><option key={c}>{c}</option>)}</select><select className={inputCls} aria-label="Part source" value={kind} onChange={e=>setKind(e.target.value)}><option value="">All parts</option><option value="custom">Custom parts</option><option value="purchased">Purchased</option><option value="existing">Existing stock</option><option value="hardware">Standard hardware</option></select></div><p className="text-xs text-muted-foreground" role="status">{filtered.length} matching parts</p><div className="max-h-52 space-y-1 overflow-auto">{filtered.map(p=><button key={p.id} className="block w-full rounded-lg border border-border px-3 py-2 text-left text-sm hover:bg-accent" disabled={!ready} onClick={()=>controls.current?.choose(p.id)}>{p.name}{p.variant?' · '+p.variant:''}<small className="block text-muted-foreground">{p.id} · {p.category} · {p.quantity} pieces</small></button>)}{!filtered.length&&<p className="p-3 text-sm">No parts match. Clear the search or change the filters.</p>}</div></div>}
  {selected?<><div><p className="text-xs text-muted-foreground">ISOLATED PART · {active?.id} · {active?.category}</p><h3 className="font-semibold">{active?.name}{active?.variant?' · '+active.variant:''}</h3></div><dl className="grid grid-cols-3 gap-2" aria-label="Overall dimensions">{active&&dimensionLabels(active).map((label,i)=><div key={label} className="rounded-lg border border-border p-2"><dt className="text-xs text-muted-foreground">{label}</dt><dd className="font-semibold">{inchFraction(active.dimensions[i])}</dd><dd className="text-xs text-muted-foreground">{exactMm(active.dimensions[i])}</dd></div>)}</dl><div className="flex flex-wrap gap-2"><button className={secondaryBtn} onClick={()=>controls.current?.fit(false)}>Fit part</button><button className={secondaryBtn} onClick={()=>controls.current?.fit(true)}>Front view</button></div></>:<><p className="text-sm">Point at any part to highlight it. Click to isolate it and see its drawing.</p><div className="flex flex-wrap gap-2">{[['overall','Whole table'],['supply','Six rolls'],['mounts','Support angles'],['pipe','Fixed pipe'],['braces','Brace plates'],['drive','Turnbuckle']].map(([id,label])=><button key={id} disabled={!ready} className={secondaryBtn} onClick={()=>controls.current?.view(id)}>{label}</button>)}</div></>}
  {error&&<div role="alert">{error} <button className={secondaryBtn} onClick={()=>setRetry(n=>n+1)}>Reopen parts view</button></div>}{!ready&&!error&&<p role="status">Opening selectable parts…</p>}
  <div className="relative"><div ref={host} aria-label="Select parts in the 3D model" style={{height:selected?'min(49vh,500px)':'min(65vh,650px)',minHeight:300,borderRadius:12,overflow:'hidden',background:'#edf0eb'}}/>{!selected&&<div className="pointer-events-none absolute bottom-3 left-3 right-3 w-fit rounded-lg bg-white/95 px-3 py-2 text-sm text-slate-800 shadow" role="status">{hoverPart?hoverPart.name+' · '+hoverPart.dimensions.map(inchFraction).join(' × ')+' · Click to isolate':'Point at a part to see its name'}</div>}</div>
  <p className="text-xs text-muted-foreground">Drag to rotate · Scroll to zoom · Right-drag to pan · {unit==='fraction'?'Dimensions rounded to 1/16″':'Exact model dimensions'}</p>
 </section>;
}
