import {Link} from 'wouter';
import {ArrowUpRight} from 'lucide-react';
import {formatMoney} from '@/lib/format';
type Totals={contractCents:number;changeOrderCents:number;expenseCents:number;stockCostCents:number;laborCostCents:number;invoicedCents:number;paidCents:number;dueNowCents:number;retainageHeldCents:number;missingRateMinutes:number;unknownStockQuantity:number;historicalMovementsWithoutCost:number;salaryEstimated:boolean};
export default function JobMoneyGraphs({id,totals:t}:{id:number;totals:Totals}){
 const incomplete=t.missingRateMinutes>0||t.unknownStockQuantity>0||t.historicalMovementsWithoutCost>0;
 const costs=[{label:'Contract + approved extras',value:t.contractCents+t.changeOrderCents,href:`/project/${id}?tab=overview`,color:'bg-indigo-500'},{label:'Stock used',value:t.stockCostCents,href:`/project/${id}?tab=materials`,color:'bg-teal-600'},{label:'Recorded labor',value:t.laborCostCents,href:`/pm/time?projectId=${id}`,color:'bg-sky-600'},{label:'Direct expenses',value:t.expenseCents,href:`/finance/expenses?projectId=${id}`,color:'bg-amber-500'}];
 const invoiceHref=`/finance/invoices?projectId=${id}`;
 const billing=[{label:'Billed to date',value:t.invoicedCents,href:invoiceHref,color:'bg-indigo-500'},{label:'Collected',value:t.paidCents,href:invoiceHref,color:'bg-teal-600'},{label:'Due now',value:t.dueNowCents,href:invoiceHref,color:'bg-amber-500'},{label:'Held retainage',value:t.retainageHeldCents,href:invoiceHref,color:'bg-slate-500'}];
 return <div className="grid gap-4 xl:grid-cols-2">{[{title:'Job costs & contract',rows:costs,note:'Whole-job totals. Stock purchases are excluded from direct expenses when already tracked as stock. Contract value and recorded costs are shown separately; this is not a profit calculation.'},{title:'Billing & collection',rows:billing,note:'Whole-job balances. Billed, collected, due and retained amounts overlap; do not add these bars together.'}].map(chart=>{
  const max=Math.max(1,...chart.rows.map(r=>Math.abs(r.value||0)));
  return <section key={chart.title} className="min-w-0 rounded-2xl border bg-card p-5"><h3 className="font-semibold">{chart.title}</h3><p className="mb-4 mt-1 text-xs leading-relaxed text-muted-foreground">{chart.note}</p>{chart.rows.map(r=><Link href={r.href} key={r.label} className="block min-h-16 rounded-xl p-2 hover:bg-muted"><span className="flex justify-between gap-2 text-sm"><span>{r.label}</span><strong className="shrink-0 tabular-nums">{formatMoney(r.value||0)}<ArrowUpRight className="ml-1 inline h-3 w-3" aria-hidden/></strong></span><span aria-hidden className="mt-2 block h-3 rounded-full bg-muted"><span className={`block h-full rounded-full ${r.color}`} style={{width:Math.abs(r.value||0)/max*100+'%'}}/></span></Link>)}{chart.title==='Job costs & contract'&&(incomplete||t.salaryEstimated)&&<p className="mt-3 rounded-lg bg-amber-500/10 p-3 text-xs">{incomplete?'Costs are incomplete: review missing labor rates or stock costs.':'Salary allocation is estimated from recorded hours.'}</p>}</section>;
 })}</div>;
}
