import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiRequest} from '@/lib/queryClient';
import {RetryBlock} from './RetryBlock';
export default function LaborPolicy(){
 const qc=useQueryClient(),q=useQuery<any[]>({queryKey:['hr-labor-policy'],queryFn:async()=>(await apiRequest('GET','/api/hr/labor-policy')).json()});
 const [form,setForm]=useState({effectiveDate:'',weeklyHours:40,multiplier:1.5,burdenPct:0,reviewed:false}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function save(){setBusy(true);setError('');try{await apiRequest('POST','/api/hr/labor-policy',form);await qc.invalidateQueries({queryKey:['hr-labor-policy']});await qc.invalidateQueries({queryKey:['hr-payroll-summary']});setForm(f=>({...f,reviewed:false}));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <details className="mb-6 rounded-xl border border-border bg-card p-4"><summary className="cursor-pointer font-semibold">Pay rules &amp; job labor costs</summary>{q.isError?<RetryBlock query={q}/>:<><p className="my-3 text-sm text-muted-foreground">{q.data?.length?'Dated rules apply to open payroll and job estimates.':'Straight-time estimates until you save a reviewed pay rule.'} Workweeks run Monday–Sunday. Employer burden affects job costs, not employee gross pay. Payroll deductions and net pay remain with your payroll provider.</p>{q.data?.map(r=><p key={r.effective_date} className="text-sm">From {r.effective_date}: {r.multiplier}× after {r.weekly_hours} hours · {r.burden_pct}% job cost burden</p>)}<div className="my-4 grid gap-3 sm:grid-cols-2">{[['effectiveDate','Effective Monday','date'],['weeklyHours','Weekly straight-time hours','number'],['multiplier','Overtime multiplier','number'],['burdenPct','Employer cost burden (%)','number']].map(([key,label,type])=><label className="text-sm" key={key}>{label}<input className="mt-1 block min-h-11 w-full rounded-lg border border-border bg-background p-2" type={type} step={type==='number'?'0.01':undefined} value={(form as any)[key]} onChange={e=>setForm(f=>({...f,[key]:type==='number'?Number(e.target.value):e.target.value}))}/></label>)}</div><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.reviewed} onChange={e=>setForm(f=>({...f,reviewed:e.target.checked}))}/>I reviewed these rules for all hourly employees in this Suite.</label><button className="mt-3 min-h-11 rounded-lg bg-primary px-4 text-primary-foreground disabled:opacity-50" disabled={busy||!form.reviewed||!form.effectiveDate} onClick={save}>Save dated pay rule</button>{error&&<p role="alert">{error}</p>}</>}</details>;
}
