import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiRequest} from '@/lib/queryClient';
import {useApiMutation} from '@/hooks/useApiMutation';
import {inputCls,primaryBtn,secondaryBtn} from '@/lib/ui-styles';
import {formatMoney} from '@/lib/format';
import {useAuth} from '@/lib/auth';
export default function MarketingSpending({site,start,end}:{site:string;start:string;end:string}){
 const {user}=useAuth(),manager=['owner','manager'].includes(user?.role||'');
 const qc=useQueryClient();const [editing,setEditing]=useState<any>(null),[date,setDate]=useState(end),[channel,setChannel]=useState('google'),[amount,setAmount]=useState(''),[campaign,setCampaign]=useState(''),[notes,setNotes]=useState(''),[error,setError]=useState('');
 const rows=useQuery<any[]>({queryKey:['marketing-spending',site],queryFn:async()=>(await apiRequest('GET','/api/marketing/spending?site='+site)).json()});
 const save=useApiMutation({request:()=>({method:editing?'PATCH':'POST',url:'/api/marketing/spending'+(editing?'/'+editing.id:''),body:{site,date,channel,amountCents:Math.round(Number(amount)*100),campaign,notes,version:editing?.version}}),invalidate:[['marketing-spending'],['marketing-growth']],successTitle:'Spending saved',errorTitle:'Could not save spending',onSuccess:()=>{setAmount('');setEditing(null);setCampaign('');setNotes('');}});
 async function change(url:string,method:string,body:object){setError('');try{await apiRequest(method,url,body);await qc.invalidateQueries({queryKey:['marketing-spending']});await qc.invalidateQueries({queryKey:['marketing-growth']});}catch(e:any){setError(e.message);}}
 return <section className="space-y-3 rounded-xl border p-4"><h3 className="font-semibold">Ad spending · CJM {site}</h3><p className="text-sm text-muted-foreground">Dated entries apply to any report containing that date. Entries replace provider totals for the same channel in that period; enter all spending for that channel. Other channels remain separate.</p>
 {manager&&<form className="grid gap-3 sm:grid-cols-3" onSubmit={e=>{e.preventDefault();if(!/^\d+(\.\d{1,2})?$/.test(amount)){setError('Enter a valid amount.');return;}save.mutate();}}>
 <label>Date<input required type="date" max={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)} className={inputCls}/></label><label>Channel<select value={channel} onChange={e=>setChannel(e.target.value)} className={inputCls}>{['google','meta','microsoft','other'].map(x=><option key={x}>{x}</option>)}</select></label><label>Amount ($)<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} className={inputCls}/></label><label>Campaign (optional)<input value={campaign} onChange={e=>setCampaign(e.target.value)} maxLength={100} className={inputCls}/></label><label>Notes<input value={notes} onChange={e=>setNotes(e.target.value)} maxLength={1000} className={inputCls}/></label><button className={primaryBtn} disabled={save.isPending}>{editing?'Save changes':'Add spending'}</button></form>}
 {error&&<p role="alert">{error}</p>}{rows.isError?<p role="alert">Could not load spending. <button onClick={()=>rows.refetch()} className={secondaryBtn}>Retry</button></p>:<details><summary className="cursor-pointer">Spending history ({rows.data?.length||0})</summary><div className="space-y-2 mt-3">{rows.data?.map(r=><div key={r.id} className="border rounded-lg p-3 flex flex-wrap gap-3 items-center"><span>{r.date} · {r.channel} · {formatMoney(r.amount_cents)} {r.campaign} {r.archived_at?'· Archived':''}</span>{manager&&<><button className={secondaryBtn} onClick={()=>{setEditing(r);setDate(r.date);setChannel(r.channel);setAmount((r.amount_cents/100).toFixed(2));setCampaign(r.campaign);setNotes(r.notes);}}>Edit</button><button className={secondaryBtn} onClick={()=>change('/api/marketing/spending/'+r.id+'/archive','POST',{version:r.version,restore:!!r.archived_at})}>{r.archived_at?'Restore':'Archive'}</button></>}</div>)}</div></details>}
 {manager&&<button className={secondaryBtn} onClick={()=>change('/api/marketing/growth/spend','DELETE',{site,start,end})}>Remove old period override</button>}<p className="text-xs text-muted-foreground">Removing an old period override restores available provider totals. Dated entries remain until archived.</p></section>;
}
