import {useState,useEffect} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {apiRequest} from '@/lib/queryClient';
import {inputCls,primaryBtn,secondaryBtn} from '@/lib/ui-styles';
import {portfolioServices,portfolioDomains} from '@shared/portfolio';
import QRCode from 'qrcode';
export function MarketingCampaigns({site}:{site:string}){
 const qc=useQueryClient(),[name,setName]=useState(''),[path,setPath]=useState('/'),[channel,setChannel]=useState('google|organic'),[message,setMessage]=useState(''),[qr,setQr]=useState('');
 const links=useQuery<any[]>({queryKey:['marketing-links',site],queryFn:async()=>(await apiRequest('GET','/api/marketing/links?site='+site)).json()});
 const link=new URL(path.startsWith('/')&&!path.startsWith('//')?path:'/',portfolioDomains[site]);const [source,medium]=channel.split('|');link.search='';link.searchParams.set('utm_source',source);link.searchParams.set('utm_medium',medium);link.searchParams.set('utm_campaign',name.replace(/[^\w.-]/g,'_').slice(0,80)||'campaign');
 useEffect(()=>setQr(''),[link.href]);
 async function save(){try{await apiRequest('POST','/api/marketing/links',{site,name,url:link.href});await qc.invalidateQueries({queryKey:['marketing-links']});setMessage('Campaign saved.');}catch(e:any){setMessage(e.message);}}
 return <section className="space-y-4 border rounded-xl p-4"><h3 className="font-semibold">Campaign links</h3><div className="grid gap-3 sm:grid-cols-2"><label>Campaign name<input className={inputCls} value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><label>Placement<select aria-label="Placement" className={inputCls} value={channel} onChange={e=>setChannel(e.target.value)}>{[['google|organic','Google Business Profile'],['bing|organic','Bing Places'],['google|cpc','Google Ads'],['facebook|paid_social','Facebook ads'],['instagram|paid_social','Instagram ads'],['facebook|social','Facebook post'],['instagram|social','Instagram post'],['print|qr','Printed QR code']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Landing page<select aria-label="Landing page" className={inputCls} value={path} onChange={e=>setPath(e.target.value)}><option value="/">Homepage</option>{Object.entries(portfolioServices[site]).map(([v,l])=><option key={v} value={'/services/'+v}>{l}</option>)}</select></label><label>Or public page path<input className={inputCls} value={path} onChange={e=>setPath(e.target.value)} placeholder="/work/123"/></label></div><input aria-label="Campaign link" className={inputCls} readOnly value={link.href}/><div className="flex flex-wrap gap-2"><button className={primaryBtn} disabled={!name.trim()} onClick={save}>Save campaign</button><button className={secondaryBtn} onClick={async()=>{try{await navigator.clipboard.writeText(link.href);setMessage('Link copied.');}catch{setMessage('Select the link above to copy it.');}}}>Copy link</button><button className={secondaryBtn} onClick={async()=>setQr(await QRCode.toDataURL(link.href,{width:320,margin:2}))}>Create QR code</button></div>{qr&&<a href={qr} download="campaign-qr.png"><img src={qr} alt="Download campaign QR code" width="240" height="240"/>Download QR</a>}{message&&<p role="status">{message}</p>}
 {links.isError?<p role="alert">Could not load saved campaigns. <button onClick={()=>links.refetch()}>Retry</button></p>:<ul className="space-y-3">{links.data?.map(r=><li key={r.id} className="p-3 rounded-lg border break-all"><a href={r.url} target="_blank" rel="noreferrer">{r.name}</a><p className="text-xs text-muted-foreground">{r.url}</p></li>)}</ul>}</section>;
}
export function MarketingOutcomes({site}:{site:string}){
 const [error,setError]=useState('');const rows=useQuery<any[]>({queryKey:['marketing-outcomes',site],queryFn:async()=>(await apiRequest('GET','/api/marketing/outcomes?site='+site)).json()});
 return <details className="border rounded-xl p-4"><summary>Lead outcome delivery</summary><p className="text-sm my-3">Accepted means Google received the request. Uncertain deliveries are not replayed to avoid double counting.</p>{rows.isError?<button onClick={()=>rows.refetch()}>Could not load outcomes · Retry</button>:rows.data?.map(r=><div key={r.id} className="border-t py-3 text-sm"><a href={'#/crm/leads?lead='+r.lead_id}>Inquiry #{r.lead_id}</a> · {r.event_name} · {r.state}<p>{r.last_error}</p>{r.state==='failed'&&/^Google HTTP (429|5\d\d)$/.test(r.last_error||'')&&r.occurred_at>Date.now()-72*3600000&&<button className={secondaryBtn} onClick={async()=>{try{await apiRequest('POST',`/api/marketing/outcomes/${r.id}/retry`,{});await rows.refetch();}catch(e:any){setError(e.message);}}}>Retry confirmed failure</button>}</div>)}{error&&<p role="alert">{error}</p>}</details>;
}
export function MarketingHistory(){const q=useQuery<any[]>({queryKey:['marketing-history'],queryFn:async()=>(await apiRequest('GET','/api/marketing/history')).json()});return <details className="border rounded-xl p-4 mt-4"><summary>Recent changes</summary>{q.isError?<button onClick={()=>q.refetch()}>Could not load history · Retry</button>:q.data?.map(r=><p className="py-2 border-b text-sm" key={r.id}>{new Date(r.created_at).toLocaleString()} · {r.user_name} · {r.action.replace('marketing.','').replaceAll('_',' ')} · {r.target_name||r.target_id||''}</p>)}</details>;}
export function exportMarketingReport(report:any){const rows=[['Business',report.brand.domain],['Period',report.current.start,report.current.end],['Definitions','Booked is won quote value; collected is payments. Sources follow inquiry attribution.'],['Source','Medium','Campaign','Leads','Qualified','Quoted','Won','Booked dollars','Collected dollars'],...report.current.bySource.map((r:any)=>[r.source,r.medium,r.campaign,r.leads,r.qualified,r.quoted,r.won,(r.bookedCents/100).toFixed(2),(r.collectedCents/100).toFixed(2)])];const csv=rows.map(r=>r.map((v:any)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`marketing-${report.site}-${report.current.end}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function MarketingPreferences(){const [site,setSite]=useState('metals');const q=useQuery<any>({queryKey:['marketing-preferences',site],queryFn:async()=>(await apiRequest('GET','/api/marketing/preferences/'+site)).json()});return <section className="border rounded-xl p-4 mt-4"><h3 className="font-medium">Business preferences</h3><select aria-label="Preferences business" className={inputCls} value={site} onChange={e=>setSite(e.target.value)}>{Object.keys(portfolioDomains).map(s=><option key={s}>{s}</option>)}</select>{q.isError?<button onClick={()=>q.refetch()}>Could not load preferences · Retry</button>:q.data?<PreferencesForm key={site+':'+q.data.version} data={q.data} reload={()=>q.refetch()}/>:<p>Loading…</p>}</section>;}
function PreferencesForm({data,reload}:{data:any;reload:()=>void}){const [stale,setStale]=useState(data.staleDays??''),[follow,setFollow]=useState(data.followUpDays??''),[url,setUrl]=useState(data.googleProfileUrl||''),[digest,setDigest]=useState(!!data.digest),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);return <form className="space-y-3 mt-3" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await apiRequest('PUT','/api/marketing/preferences/'+data.site,{version:data.version,staleDays:stale===''?null:Number(stale),followUpDays:follow===''?null:Number(follow),googleProfileUrl:url,digest});reload();}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}}><p className="text-sm">Blank day counts inherit the shared automation settings. A blank review link uses the verified default for this business.</p><label>Stale inquiry after (days)<input className={inputCls} type="number" min="1" max="90" value={stale} onChange={e=>setStale(e.target.value)}/></label><label>Quote follow-up after (days)<input className={inputCls} type="number" min="1" max="90" value={follow} onChange={e=>setFollow(e.target.value)}/></label><label>Google review profile link<input className={inputCls} type="url" value={url} onChange={e=>setUrl(e.target.value)}/></label><label className="flex gap-2"><input type="checkbox" checked={digest} onChange={e=>setDigest(e.target.checked)}/>Include this business in the existing owner email digest</label><button className={primaryBtn} disabled={busy}>Save business preferences</button>{message&&<p role="alert">{message}</p>}</form>;}

export function MarketingReviewChecks(){const qc=useQueryClient();const [message,setMessage]=useState('');const q=useQuery<any[]>({queryKey:['marketing-review-checks'],queryFn:async()=>(await apiRequest('GET','/api/marketing/review-checks')).json()});return <details className="border rounded-xl p-4 mt-4"><summary>Review data checks</summary>{q.isError?<button onClick={()=>q.refetch()}>Could not check reviews · Retry</button>:q.data?.length?q.data.map(r=><div key={r.id} className="border-t py-3"><p>Review #{r.id} · {r.author} · {r.invalid?'Invalid rating or date; edit this review.':`Saved as ${r.site}; linked invitation belongs to ${r.expected}.`}</p>{r.expected&&r.expected!==r.site&&<button className={secondaryBtn} onClick={async()=>{try{await apiRequest('POST',`/api/marketing/review-checks/${r.id}/repair`,{version:r.version});await q.refetch();qc.invalidateQueries({queryKey:['marketing']});}catch(e:any){setMessage(e.message);}}}>Correct business and return to draft</button>}</div>):<p className="mt-3 text-sm">No known review assignment or validation issues found.</p>}{message&&<p role="alert">{message}</p>}</details>;}
