import { useEffect, useMemo, useRef, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Area, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowUpRight, BarChart3, CheckCircle2, Globe2, RefreshCw, ShieldCheck, TrendingUp } from 'lucide-react';
import { apiRequest } from '@/lib/queryClient';
import { inputCls, secondaryBtn } from '@/lib/ui-styles';
import { useMarketingPlace } from '@/hooks/useMarketingPlace';
import { aiReferralProvider } from '@shared/ai-referrals';
import { coveredSum, metric, ratio, reportRows, searchComparisonRows, searchSummary, trendRows, websiteNames, type AnalyticsPeriod, type AnalyticsRow, type ReportName, type Website, type WebsiteAnalytics as AnalyticsResponse, type WebsiteResult } from '@shared/website-analytics';
import AnalyticsTable, { type AnalyticsColumn } from './WebsiteAnalyticsTable';
import SearchConnections from './SearchConnections';
import { AudienceVisuals, OutcomeVisuals, PageExplorer, SearchVisuals, TrafficVisuals, WebsiteComparison } from './WebsiteAnalyticsVisuals';

const number=(value:unknown)=>typeof value==='number'?value.toLocaleString(undefined,{maximumFractionDigits:0}):'—';
const percent=(value:unknown)=>typeof value==='number'?(value*100).toFixed(1)+'%':'—';
const money=(value:unknown)=>typeof value==='number'?(value/100).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0}):'—';
const decimal=(value:unknown)=>typeof value==='number'?value.toFixed(1):'—';
const textColumn=(key:string,label:string):AnalyticsColumn=>({key,label});
const countColumn=(key:string,label:string):AnalyticsColumn=>({key,label,numeric:true,format:number});
const percentColumn=(key:string,label:string):AnalyticsColumn=>({key,label,numeric:true,format:percent,export:v=>percent(v)});
const moneyColumn=(key:string,label:string):AnalyticsColumn=>({key,label,numeric:true,format:money,export:v=>money(v)});
const siteColumn=textColumn('website','Website');
const sections=[['overview','Summary'],['search','Searches'],['traffic','Traffic sources'],['pages','Pages'],['audience','Audience'],['outcomes','Inquiries & sales'],['health','Data & connections']] as const;
type Section=typeof sections[number][0];
const yesterday=()=>{const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());return new Date(Date.parse(today)-86400000).toISOString().slice(0,10);};
const summaryValue=(period:AnalyticsPeriod,key:string)=>metric(period.reports.summary?.rows[0],key);
const reportPartial=(period:AnalyticsPeriod)=>!!period.reports.summary?.partial;
const labelReport=(name:string)=>name.replace(/^analytics:/,'').replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());

function Stat({label,value,previous,detail,format=number,comparable=true}:{label:string;value:number|null;previous?:number|null;detail:string;format?:(v:unknown)=>string;comparable?:boolean}) {
  const change=comparable&&value!=null&&previous!=null&&previous>0?(value-previous)/previous:null;
  return <div className="rounded-2xl border border-border bg-card p-4 sm:p-5"><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">{format(value)}</p><p className="mt-2 text-xs text-muted-foreground">{change!=null?<span className="font-medium text-foreground">{change>0?'+':''}{percent(change)} </span>:null}{previous!==undefined?(comparable&&previous!=null?`vs ${format(previous)} previously`:'Comparison unavailable'):detail}</p>{previous!==undefined&&<p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">{detail}</p>}</div>;
}
function ReportNotice({sites,names}:{sites:WebsiteResult[];names:(ReportName|'search'|'queries')[]}) {
  const issues=sites.flatMap(s=>names.flatMap(name=>{
    const r=name==='search'||name==='queries'?s.current[name]:s.current.reports[name];
    const status=s.connections.googleStatus.find(status=>status.kind===(name==='search'||name==='queries'?name:'analytics:'+name));
    const state=!r?'not available for these dates':status?.error?'refresh failed; showing saved data':r.partial?'limited results':r.thresholded||r.sampled?'provider privacy limits or sampling':r.legacy?'basic snapshot; refresh for full detail':Date.now()-r.fetchedAt>24*3600000?'more than 24 hours old':null;
    return state?[`${websiteNames[s.site]} · ${labelReport(name)}: ${state}`]:[];
  }));
  if(!issues.length)return null;
  return <details className="rounded-xl border border-amber-500/25 bg-amber-500/5 p-3 text-xs"><summary className="cursor-pointer font-medium">Data coverage · {issues.length} report{issues.length===1?'':'s'} to check</summary><ul className="mt-2 space-y-1 text-muted-foreground">{issues.map(issue=><li key={issue}>{issue}</li>)}</ul><p className="mt-2">Refresh reports to retrieve connected data for these dates. Missing data is shown as —, not zero.</p></details>;
}
function Trend({sites,filename}:{sites:WebsiteResult[];filename:string}) {
  const [measure,setMeasure]=useState('sessions');
  const rows=useMemo(()=>trendRows(sites,measure==='sessions'?'daily':'searchDaily',measure),[sites,measure]);
  const available=rows.some(row=>row.current!=null);
  return <section aria-label="Performance trend" className="min-w-0 rounded-2xl border bg-card p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Performance over time</h3><p className="mt-1 text-xs text-muted-foreground">Solid: selected period · Dashed: preceding period, aligned by day</p></div><select aria-label="Trend metric" className={inputCls+' w-auto'} value={measure} onChange={e=>setMeasure(e.target.value)}><option value="sessions">Website sessions</option><option value="clicks">Google clicks</option><option value="impressions">Google impressions</option></select></div><div className="mt-6 h-64 min-w-0">{available?<ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows} margin={{top:5,right:8,bottom:4,left:-20}}><CartesianGrid vertical={false} stroke="currentColor" opacity={0.08}/><XAxis dataKey="date" tickFormatter={v=>String(v).slice(5)} minTickGap={35} fontSize={11}/><YAxis fontSize={11} allowDecimals={false}/><Tooltip content={({active,payload})=>{if(!active||!payload?.[0])return null;const row=payload[0].payload;return <div className="rounded-xl border bg-popover p-3 text-xs shadow-lg"><p className="font-semibold">{row.date}</p><p>{number(row.current)} · {row.coverage}/{sites.length} sites</p><p className="mt-1 text-muted-foreground">{row.previousDate}: {number(row.previous)} · {row.previousCoverage}/{sites.length} sites</p></div>;}}/><Area name="Selected period" type="monotone" dataKey="current" stroke="#0f766e" fill="#0f766e" fillOpacity={0.1} strokeWidth={2} isAnimationActive={false}/><Line name="Previous period" type="monotone" dataKey="previous" stroke="#94a3b8" strokeDasharray="5 5" dot={false} strokeWidth={2} isAnimationActive={false}/></ComposedChart></ResponsiveContainer>:<div className="flex h-full flex-col items-center justify-center rounded-xl bg-muted/30 text-sm text-muted-foreground"><BarChart3 size={28} className="mb-3"/>Daily reports are not available for these dates.</div>}</div><p className="mt-3 text-xs text-muted-foreground">Hover for dates and website coverage. Missing search days remain gaps; finalized Google search data may lag behind Analytics.</p><details className="mt-4"><summary className="cursor-pointer text-xs font-medium">View or export daily values</summary><div className="mt-3"><AnalyticsTable title="Daily performance" description="Current and previous dates are aligned by day. Check coverage before comparing totals." rows={rows} columns={[textColumn('date','Date'),countColumn('current','Selected period'),countColumn('coverage','Sites reporting'),textColumn('previousDate','Previous date'),countColumn('previous','Previous period'),countColumn('previousCoverage','Previous sites')]} filename={filename+'-daily-'+measure}/></div></details></section>;
}

function Summary({sites,onSite,onSection,filename}:{sites:WebsiteResult[];onSite:(s:Website)=>void;onSection:(s:Section)=>void;filename:string}) {
  const c=sites.map(s=>s.current),p=sites.map(s=>s.previous),search=searchSummary(c),prior=searchSummary(p);
  const summary=(key:string)=>{
    const values=c.map(p=>summaryValue(p,key)),previous=p.map(p=>summaryValue(p,key));
    const sum=coveredSum(values);
    return {value:sum.value,previous:coveredSum(previous).value,comparable:values.every((v,i)=>(v==null)===(previous[i]==null))&&!c.some(reportPartial)&&!p.some(reportPartial),detail:`${sum.covered}/${sum.total} websites reporting${c.some(reportPartial)?' · limited results':''}`};
  };
  const business=(key:keyof AnalyticsPeriod['totals'])=>({value:c.reduce((n,r)=>n+r.totals[key],0),previous:p.reduce((n,r)=>n+r.totals[key],0)});
  const searchComparable=c.every((r,i)=>!!r.searchTotals===!!p[i].searchTotals);
  const websiteRows:AnalyticsRow[]=sites.map(s=>({site:s.site,website:websiteNames[s.site],sessions:summaryValue(s.current,'sessions'),users:summaryValue(s.current,'totalUsers'),clicks:s.current.searchTotals?.clicks??null,impressions:s.current.searchTotals?.impressions??null,bingClicks:s.current.bing.totals?.clicks??null,leads:s.current.totals.leads,won:s.current.totals.won,booked:s.current.totals.bookedCents}));
  const opportunities=sites.flatMap(s=>(s.current.search?.rows||[]).filter(r=>(metric(r,'impressions')||0)>=50&&(metric(r,'ctr')||0)<0.02&&(metric(r,'position')||100)<=20).map((r):AnalyticsRow & {site:Website;website:string}=>({...r,site:s.site,website:websiteNames[s.site]}))).sort((a,b)=>(metric(b,'impressions')||0)-(metric(a,'impressions')||0)).slice(0,4);
  const awaiting=c.reduce((sum,r)=>sum+r.totals.awaitingContact,0);
  return <>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-3"><Stat label="Website sessions" {...summary('sessions')}/><Stat label={sites.length>1?'Users across websites':'Website users'} {...summary('totalUsers')} detail={sites.length>1?`${summary('totalUsers').detail} · not deduplicated across sites`:summary('totalUsers').detail}/><Stat label="Google search clicks" value={search.clicks.value} previous={prior.clicks.value} comparable={searchComparable} detail={`${search.clicks.covered}/${sites.length} sites · Google web search`}/><Stat label="Google search impressions" value={search.impressions.value} previous={prior.impressions.value} comparable={searchComparable} detail={`${search.impressions.covered}/${sites.length} sites · Appearances in Google web results`}/><Stat label="Saved inquiries" {...business('leads')} detail="Inquiries received during the period; test records excluded"/><Stat label="Won jobs" {...business('won')} detail="Outcomes to date for inquiries received in the period"/></div>
    <ReportNotice sites={sites} names={['summary','daily','searchDaily']}/><WebsiteComparison sites={sites} onPages={()=>onSection('pages')}/><Trend sites={sites} filename={filename}/>
    <AnalyticsTable title="Every website at a glance" description="Compare full website traffic with recorded business outcomes. Click a website to focus its reports. Bing clicks cover only Bing’s available dates." filename={filename+'-websites'} rows={websiteRows} sortKey="sessions" columns={[{...siteColumn,format:(value,row)=><button className="text-left font-medium text-primary underline underline-offset-4" onClick={()=>onSite(row.site as Website)}>{value}<ArrowUpRight size={12} className="ml-1 inline"/></button>},countColumn('sessions','Sessions'),countColumn('users','Users'),countColumn('clicks','Google clicks'),countColumn('impressions','Google impressions'),countColumn('bingClicks','Bing clicks'),countColumn('leads','Inquiries'),countColumn('won','Won'),moneyColumn('booked','Booked value')]}/>
    <section className="rounded-2xl border bg-card p-5"><div className="mb-4 flex items-center gap-2"><TrendingUp size={18} className="text-teal-700"/><h3 className="font-semibold">What to look at next</h3></div><div className="grid gap-3 md:grid-cols-2">{awaiting>0&&<button onClick={()=>onSection('outcomes')} className="rounded-xl border bg-muted/20 p-4 text-left"><p className="font-medium">{awaiting} inquiries awaiting first contact</p><p className="mt-1 text-xs text-muted-foreground">Review follow-up before spending more to attract traffic.</p></button>}{opportunities.map((r,i)=><button key={i} onClick={()=>{onSite(r.site);onSection('pages');}} className="rounded-xl border bg-muted/20 p-4 text-left"><p className="text-xs font-medium text-teal-700">{r.website} · Search opportunity</p><p className="mt-1 break-all text-sm font-medium">{String(r.page)}</p><p className="mt-2 text-xs text-muted-foreground">{number(r.impressions)} impressions · {percent(r.ctr)} click rate · position {decimal(r.position)}. Review the title and relevance to the search.</p></button>)}</div>{!awaiting&&!opportunities.length&&<p className="text-sm text-muted-foreground">No high-priority flags from the available reports. Review search terms and page engagement for more detail.</p>}<p className="mt-3 text-xs text-muted-foreground">Search suggestions use pages with at least 50 impressions, under 2% click rate and an average position in the top 20. These are review prompts, not diagnoses.</p></section>
  </>;
}

function SearchAnalysis({sites,filename}:{sites:WebsiteResult[];filename:string}) {
  const totals=searchSummary(sites.map(s=>s.current));
  const columns=[siteColumn,textColumn('query','Search term'),countColumn('clicks','Clicks'),countColumn('impressions','Impressions'),percentColumn('ctr','Click rate'),{key:'position',label:'Average position',numeric:true,format:decimal}];
  const bingQueries=sites.flatMap(s=>s.current.bing.topQueries.map(r=>({...r,website:websiteNames[s.site]})));
  const bingPages=sites.flatMap(s=>s.current.bing.topPages.map(r=>({...r,website:websiteNames[s.site]})));
  return <><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Google clicks" value={totals.clicks.value} detail={`${totals.clicks.covered}/${sites.length} sites reporting`}/><Stat label="Google impressions" value={totals.impressions.value} detail="Property totals, not the sum of keyword rows"/><Stat label="Google click-through rate" value={totals.ctr} format={percent} detail="Total clicks ÷ total impressions"/><Stat label="Average Google position" value={totals.position} format={decimal} detail="Impression-weighted; a lower number is better"/></div><p className="text-xs leading-relaxed text-muted-foreground">Google web search only. Search Console hides some searches for privacy and returns top rows; keyword totals will not equal property totals. Rankings vary by location and device. Search clicks are different from Analytics sessions.</p><ReportNotice sites={sites} names={['queries','queryPages','searchDevices','searchCountries','siteSearch']}/>
    <SearchVisuals sites={sites}/><AnalyticsTable title="Google search terms" description="What people searched before your website appeared. Sort by impressions to find visibility, or clicks to find traffic. Previous clicks compare the same reported term; — means no prior row was reported." rows={searchComparisonRows(sites,'queries')} columns={[...columns,countColumn('previousClicks','Previous clicks'),countColumn('clickChange','Click change')]} sortKey="clicks" filename={filename+'-google-queries'}/>
    <AnalyticsTable title="Search terms and their pages" description="The page Google showed for each reported search. Page-level impressions can differ from property totals." rows={reportRows(sites,'queryPages')} columns={[siteColumn,textColumn('query','Search term'),textColumn('page','Page'),...columns.slice(2)]} sortKey="impressions" filename={filename+'-query-pages'}/>
    <div className="grid min-w-0 gap-4 xl:grid-cols-2">{(['searchDevices','searchCountries'] as const).map(name=><AnalyticsTable key={name} title={name==='searchDevices'?'Google search by device':'Google search by country'} description={name==='searchCountries'?'Search Console uses three-letter country codes.':undefined} rows={reportRows(sites,name)} columns={[siteColumn,textColumn(name==='searchDevices'?'device':'country',name==='searchDevices'?'Device':'Country'),...columns.slice(2)]} sortKey="clicks" filename={filename+'-'+name}/>)}</div>
    <AnalyticsTable title="Bing performance by website" description="Bing’s available dates can cover less than the selected range. A missing report does not mean zero search traffic." rows={sites.map(s=>({website:websiteNames[s.site],clicks:s.current.bing.totals?.clicks??null,impressions:s.current.bing.totals?.impressions??null,start:s.current.bing.totals?.firstDate??null,end:s.current.bing.totals?.lastDate??null,days:s.current.bing.totals?.reportedDays??null}))} columns={[siteColumn,countColumn('clicks','Clicks'),countColumn('impressions','Impressions'),textColumn('start','First available day'),textColumn('end','Last available day'),countColumn('days','Reported days')]} filename={filename+'-bing'} sortKey="clicks"/>
    {[{title:'Bing search terms',rows:bingQueries,label:'Search term'},{title:'Bing search pages',rows:bingPages,label:'Page'}].map(g=><AnalyticsTable key={g.title} title={g.title} description="Provider weekly snapshot, independent of the selected period totals. The snapshot date is shown on every row." rows={g.rows} columns={[siteColumn,textColumn('label',g.label),textColumn('date','Snapshot date'),countColumn('clicks','Clicks'),countColumn('impressions','Impressions')]} sortKey="clicks" filename={filename+'-'+g.title}/>)}
    <AnalyticsTable title="Searches inside your websites" description="Search terms recorded by enhanced measurement’s view_search_results event. Empty results may mean no searches, no site search feature, or no tracking; this is separate from Google/Bing searches. Email-like terms and long numbers are redacted." rows={reportRows(sites,'siteSearch')} columns={[siteColumn,textColumn('searchTerm','Internal search term'),countColumn('eventCount','Search events')]} sortKey="eventCount" filename={filename+'-internal-search'}/>
  </>;
}

function TrafficAnalysis({sites,filename}:{sites:WebsiteResult[];filename:string}) {
  const channels=reportRows(sites,'channels');
  const rows=channels.map(row=>({...row,engagementRate:ratio(metric(row,'engagedSessions'),metric(row,'sessions')),ai:aiReferralProvider(String(row.sessionSource||''),String(row.sessionMedium||''))}));
  return <><ReportNotice sites={sites} names={['channels','events']}/><TrafficVisuals sites={sites}/><AnalyticsTable title="Traffic sources and campaigns" description="Session-based acquisition from production websites. Source identifies who sent the visit; medium describes the channel; campaign comes from tracking tags or linked ad accounts. Engagement rate is engaged sessions ÷ sessions." rows={rows} columns={[siteColumn,textColumn('sessionDefaultChannelGroup','Channel'),textColumn('sessionSource','Source'),textColumn('sessionMedium','Medium'),textColumn('sessionCampaignName','Campaign'),countColumn('sessions','Sessions'),countColumn('engagedSessions','Engaged sessions'),percentColumn('engagementRate','Engagement'),countColumn('keyEvents','Key events')]} sortKey="sessions" filename={filename+'-sources'}/>
    <AnalyticsTable title="AI referrals" description="Recognized referring visits from ChatGPT, Perplexity and other AI tools. These are not AI mentions or citations. Referrals without a source cannot be identified, and Google AI traffic can appear under ordinary search." rows={rows.filter(r=>r.ai)} columns={[siteColumn,textColumn('ai','AI source'),textColumn('sessionSource','Referrer'),countColumn('sessions','Sessions'),countColumn('engagedSessions','Engaged sessions'),countColumn('keyEvents','Key events')]} sortKey="sessions" filename={filename+'-ai-referrals'}/>
    <AnalyticsTable title="Website actions and events" description="Events actually recorded by Analytics, such as page_view, form submissions or clicks when tracked. Key events depend on your Analytics configuration and are not the same as saved inquiries or won jobs. Counts may include repeated actions." rows={reportRows(sites,'events')} columns={[siteColumn,textColumn('eventName','Event'),countColumn('eventCount','Event count'),countColumn('keyEvents','Key events')]} sortKey="eventCount" filename={filename+'-events'}/></>;
}

function PageAnalysis({sites,filename}:{sites:WebsiteResult[];filename:string}) {
  const landing=reportRows(sites,'landing').map(row=>({...row,engagementRate:ratio(metric(row,'engagedSessions'),metric(row,'sessions'))}));
  const pageColumn=(key:string):AnalyticsColumn=>({key,label:'Page',format:(value,row)=>{
    const domain=sites.find(s=>s.site===row.site)?.domain;
    return typeof value==='string'&&value.startsWith('/')&&!value.startsWith('//')&&!['/private','/other'].includes(value)&&domain?<a className="underline underline-offset-4" target="_blank" rel="noopener noreferrer" href={'https://'+domain+value}>{value}<ArrowUpRight size={12} className="ml-1 inline"/></a>:value??'—';
  }});
  return <><ReportNotice sites={sites} names={['landing','pages','search']}/><PageExplorer sites={sites}/><AnalyticsTable title="Landing pages" description="Where sessions began. Query strings and private customer links are removed. A session can include several page views; landing-page sessions and page views measure different things." rows={landing} columns={[siteColumn,pageColumn('landingPagePlusQueryString'),countColumn('sessions','Sessions'),countColumn('engagedSessions','Engaged sessions'),percentColumn('engagementRate','Engagement'),countColumn('keyEvents','Key events')]} sortKey="sessions" filename={filename+'-landing-pages'}/>
    <AnalyticsTable title="Pages people viewed" description="Page views include repeat views. Engagement time is the recorded total time the page was in the foreground, not a load-speed measurement." rows={reportRows(sites,'pages').map(r=>({...r,engagementMinutes:metric(r,'userEngagementDuration')===null?null:Number(r.userEngagementDuration)/60}))} columns={[siteColumn,pageColumn('pagePath'),countColumn('screenPageViews','Views'),{key:'engagementMinutes',label:'Engagement minutes',numeric:true,format:decimal}]} sortKey="screenPageViews" filename={filename+'-page-views'}/>
    <AnalyticsTable title="Pages in Google search" description="Search performance by canonical page. Sort by impressions to identify pages that are visible but receive few clicks." rows={searchComparisonRows(sites,'search')} columns={[siteColumn,pageColumn('page'),countColumn('clicks','Clicks'),countColumn('impressions','Impressions'),percentColumn('ctr','Click rate'),{key:'position',label:'Average position',numeric:true,format:decimal},countColumn('previousClicks','Previous clicks'),countColumn('clickChange','Click change')]} sortKey="impressions" filename={filename+'-search-pages'}/></>;
}

function AudienceAnalysis({sites,filename}:{sites:WebsiteResult[];filename:string}) {
  const summary=sites.map(s=>s.current.reports.summary?.rows[0]);
  return <><div className="grid grid-cols-2 gap-3"><Stat label="New users" value={coveredSum(summary.map(r=>metric(r,'newUsers'))).value} detail="First visits identified by Analytics; consent and cookie settings affect measurement"/><Stat label="Engaged sessions" value={coveredSum(summary.map(r=>metric(r,'engagedSessions'))).value} detail="Sessions that met Analytics’ engagement criteria"/></div><ReportNotice sites={sites} names={['devices','locations']}/><AudienceVisuals sites={sites}/><AnalyticsTable title="Devices and browsers" description="Use this to prioritize the screens and browsers your visitors use. Breakdowns may include the same session in more than one row; do not use their sum as a substitute for the summary." rows={reportRows(sites,'devices').map(r=>({...r,engagementRate:ratio(metric(r,'engagedSessions'),metric(r,'sessions'))}))} columns={[siteColumn,textColumn('deviceCategory','Device'),textColumn('browser','Browser'),countColumn('sessions','Sessions'),percentColumn('engagementRate','Engagement')]} sortKey="sessions" filename={filename+'-devices'}/>
    <AnalyticsTable title="Visitor locations" description="Approximate country, region and city reported by Analytics. These are not individual addresses. Privacy controls, VPNs and unknown locations affect this report." rows={reportRows(sites,'locations')} columns={[siteColumn,textColumn('country','Country'),textColumn('region','Region / state'),textColumn('city','City'),countColumn('sessions','Sessions'),countColumn('engagedSessions','Engaged sessions')]} sortKey="sessions" filename={filename+'-locations'}/></>;
}

function Outcomes({sites,filename}:{sites:WebsiteResult[];filename:string}) {
  const sum=(key:keyof AnalyticsPeriod['totals'])=>sites.reduce((n,s)=>n+s.current.totals[key],0);
  const rows=sites.flatMap(s=>s.current.bySource.map(r=>({...r,website:websiteNames[s.site]})));
  return <><div className="rounded-xl border bg-muted/20 p-4 text-sm leading-relaxed">Inquiries are grouped by when they arrived. Quotes, wins, booked value and payments show their linked outcomes to date. Attribution uses the saved first source; it is separate from Analytics’ session attribution. These are not steps in a measured visitor funnel.</div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Saved inquiries" value={sum('leads')} detail="Received in the selected period"/><Stat label="Quoted inquiries" value={sum('quoted')} detail="At least one sent, accepted or declined quote"/><Stat label="Booked value" value={sum('bookedCents')} format={money} detail="Recorded value of won inquiries"/><Stat label="Collected payments" value={sum('collectedCents')} format={money} detail="Payments linked to this inquiry cohort, to date"/></div>
    <OutcomeVisuals sites={sites}/><AnalyticsTable title="Business results by website" description="Lead-to-win rate is won inquiries ÷ saved inquiries. Ad spend is available only for connected or entered channels; partial spend is flagged." rows={sites.map(s=>({website:websiteNames[s.site],...s.current.totals,winRate:ratio(s.current.totals.won,s.current.totals.leads),spend:s.current.spendCents,spendCoverage:s.current.spendPartial||s.current.missingSpendChannels.length?'Partial':s.current.spendCents==null?'Not connected':'Available channels'}))} columns={[siteColumn,countColumn('leads','Inquiries'),countColumn('qualified','Qualified'),countColumn('quoted','Quoted'),countColumn('won','Won'),percentColumn('winRate','Lead-to-win'),countColumn('awaitingContact','Awaiting contact'),moneyColumn('bookedCents','Booked'),moneyColumn('collectedCents','Collected'),moneyColumn('spend','Ad spend'),textColumn('spendCoverage','Spend coverage')]} sortKey="leads" filename={filename+'-outcomes'}/>
    <AnalyticsTable title="Sources that generated inquiries and sales" description="First-touch source, campaign and recorded landing page. Unrecorded attribution stays visible; it is not reassigned to organic search." rows={rows} columns={[siteColumn,textColumn('source','Source'),textColumn('medium','Medium'),textColumn('campaign','Campaign'),textColumn('page','Landing page'),countColumn('leads','Inquiries'),countColumn('qualified','Qualified'),countColumn('quoted','Quoted'),countColumn('won','Won'),moneyColumn('bookedCents','Booked'),moneyColumn('collectedCents','Collected')]} sortKey="leads" filename={filename+'-attribution'}/></>;
}

function DataHealth({sites}:{sites:WebsiteResult[]}) {
  return <><section className="rounded-2xl border bg-card p-5"><h3 className="flex items-center gap-2 font-semibold"><ShieldCheck size={18}/>How to read these reports</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-muted-foreground"><li>Google Analytics measures tracked visits and actions. Consent choices, blockers and untracked actions create gaps. Only the configured production hostname is included.</li><li>Google Search Console measures web-search visibility and clicks. Private search terms are withheld, and recent dates may not be finalized. It uses Pacific reporting dates; Analytics uses each property’s timezone.</li><li>Business results use Central Time and exclude staff/test inquiries. Counts across websites are added; users are not deduplicated between websites.</li><li>AI referrals are visits, not proof of a citation. Google Business Profile statistics, ad-platform delivery and AI citation counts require their own provider reports.</li><li>This dashboard reports audience and marketing performance. It does not run a technical crawl, an uptime monitor or a page-speed test.</li></ul><p className="mt-3 text-xs"><a href="https://developers.google.com/analytics/devguides/reporting/data/v1/api-schema" target="_blank" rel="noopener noreferrer" className="underline">Google Analytics metric definitions</a> · <a href="https://developers.google.com/webmaster-tools/v1/searchanalytics/query" target="_blank" rel="noopener noreferrer" className="underline">Search Console reporting limits</a></p></section>{sites.map(s=><section key={s.site} className="min-w-0 space-y-3"><h3 className="flex items-center gap-2 text-lg font-semibold"><Globe2 size={19}/>{websiteNames[s.site]}</h3><SearchConnections connection={s.connections} bing={s.current.bing} previousBing={s.previous.bing}/><details className="rounded-xl border bg-card p-4"><summary className="cursor-pointer text-sm font-medium">Individual report freshness</summary><ul className="mt-3 divide-y text-xs">{Object.entries(s.current.reports).map(([name,r])=><li key={name} className="flex flex-wrap justify-between gap-2 py-2"><span>{labelReport(name)}</span><span className="text-muted-foreground">{r?`${new Date(r.fetchedAt).toLocaleString()}${r.timeZone?' · '+r.timeZone:''}${r.partial?' · Limited':''}${r.legacy?' · Basic snapshot':''}${r.thresholded?' · Privacy limits':''}${r.sampled?' · Sampled':''}`:'Not available'}</span></li>)}</ul></details></section>)}</>;
}

export default function WebsiteAnalytics() {
  const [site,setSite]=useMarketingPlace<Website|'all'>('analyticsSite','all');
  const [start,setStart]=useMarketingPlace<string>('start',''),[end,setEnd]=useMarketingPlace<string>('end','');
  const [rawSection,setSection]=useMarketingPlace<Section>('analysis','overview');
  const section=sections.some(([key])=>key===rawSection)?rawSection:'overview';
  const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  const client=useQueryClient();
  const query=useQuery<AnalyticsResponse>({queryKey:['marketing-analytics',site,start,end],queryFn:async({signal})=>(await apiRequest('GET','/api/marketing/growth/analytics?'+new URLSearchParams({site,start,end}),undefined,{signal})).json(),staleTime:60000});
  const data=query.data,sites=data?.sites||[];
  const filename=`website-analytics-${site}-${data?.current.start||start}-${data?.current.end||end}`;
  const refresh=async()=>{
    if(!data)return;setBusy(true);setMessage('Starting report refresh…');const errors:string[]=[];let completed=0;
    for(const s of sites){if(!mounted.current)break;
      setMessage(`Refreshing ${websiteNames[s.site]} · ${completed+1} of ${sites.length}…`);
      try{const result=await(await apiRequest('POST','/api/marketing/growth/refresh',{site:s.site,start:data.current.start,end:data.current.end})).json();
        for(const period of ['current','previous'])for(const [name,status] of Object.entries(result[period]||{}))if(status!=='updated')errors.push(`${websiteNames[s.site]} · ${period} ${labelReport(name)}: ${status===true?'Already refreshing':String(status)}`);
      }catch(e){errors.push(`${websiteNames[s.site]}: ${(e as Error).message}`);}
      completed++;
    }
    await Promise.all([client.invalidateQueries({queryKey:['marketing-analytics']}),client.invalidateQueries({queryKey:['marketing-growth']})]);
    if(mounted.current){setBusy(false);setMessage(errors.length?'Refresh finished with gaps. '+errors.join('; '):`Reports refreshed for ${completed} website${completed===1?'':'s'}.`);}
  };
  const quickRange=(days:number)=>{const finish=yesterday();setEnd(finish);setStart(new Date(Date.parse(finish)-(days-1)*86400000).toISOString().slice(0,10));};
  const providerEnabled=sites.some(s=>s.connections.googleConfigured||s.connections.bingConfigured);
  return <section aria-label="Website analytics" className="min-w-0 space-y-5">
    <div className="rounded-2xl border border-teal-700/15 bg-gradient-to-br from-teal-700/10 via-card to-card p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-teal-700 dark:text-teal-300"><Globe2 size={15}/>Website reports</p><h2 className="text-2xl font-semibold tracking-tight">The full picture of your websites</h2><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Discover how people find you, what they explore and which sources bring business.</p></div><button onClick={refresh} disabled={busy||!providerEnabled} className={secondaryBtn+' print:hidden'}><RefreshCw size={15} className={busy?'animate-spin':''}/>{busy?'Refreshing…':site==='all'?'Refresh all websites':'Refresh reports'}</button></div>
    <fieldset disabled={busy} className="mt-5 grid gap-3 sm:grid-cols-3 print:hidden"><label className="text-xs font-medium">Website<select aria-label="Analytics website" className={inputCls+' mt-1'} value={site} onChange={e=>{setSite(e.target.value as Website|'all');setMessage('');}}><option value="all">All websites</option>{Object.entries(websiteNames).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label className="text-xs font-medium">From<input aria-label="Analytics start date" type="date" className={inputCls+' mt-1'} max={end||yesterday()} value={start||data?.current.start||''} onChange={e=>setStart(e.target.value)}/></label><label className="text-xs font-medium">To<input aria-label="Analytics end date" type="date" className={inputCls+' mt-1'} max={yesterday()} value={end||data?.current.end||''} onChange={e=>setEnd(e.target.value)}/></label></fieldset><div className="mt-3 flex flex-wrap items-center gap-2 print:hidden">{[7,28,90].map(days=><button disabled={busy} onClick={()=>quickRange(days)} key={days} className="rounded-full border bg-background/80 px-3 py-1.5 text-xs hover:border-primary disabled:opacity-50">Last {days} days</button>)}<span className="ml-auto text-[11px] text-muted-foreground">Completed days · Automatically compared with the preceding period</span></div></div>
    {message&&<p role="status" className="break-words rounded-xl border bg-muted/30 p-3 text-sm">{message}</p>}
    {query.isError?<div role="alert" className="rounded-xl border p-5"><p>Website analytics could not load. {(query.error as Error).message}</p><div className="mt-3 flex gap-2"><button className={secondaryBtn} onClick={()=>query.refetch()}>Retry</button><button className={secondaryBtn} onClick={()=>{setStart('');setEnd('');setSite('all');}}>Reset filters</button></div></div>:!data?<p role="status" className="rounded-xl border p-6 text-muted-foreground">Loading website analytics…</p>:<>
      <div className="flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground"><span>{data.current.start} – {data.current.end} · Previous: {data.previous.start} – {data.previous.end}</span><span>{sites.length} website{sites.length===1?'':'s'} selected</span></div>
      <nav aria-label="Analytics reports" className="flex flex-wrap gap-1 rounded-xl border bg-card p-1 print:hidden">{sections.map(([key,label])=><button key={key} aria-pressed={section===key} onClick={()=>setSection(key)} className={'rounded-lg px-3 py-2.5 text-xs font-medium transition-colors '+(section===key?'bg-foreground text-background':'text-muted-foreground hover:bg-muted')}>{label}</button>)}</nav>
      {section==='overview'&&<Summary sites={sites} onSite={setSite} onSection={setSection} filename={filename}/>}
      {section==='search'&&<SearchAnalysis sites={sites} filename={filename}/>}
      {section==='traffic'&&<TrafficAnalysis sites={sites} filename={filename}/>}
      {section==='pages'&&<PageAnalysis sites={sites} filename={filename}/>}
      {section==='audience'&&<AudienceAnalysis sites={sites} filename={filename}/>}
      {section==='outcomes'&&<Outcomes sites={sites} filename={filename}/>}
      {section==='health'&&<DataHealth sites={sites}/>}
      <p className="flex items-start gap-2 border-t pt-4 text-xs leading-relaxed text-muted-foreground"><CheckCircle2 size={14} className="mt-0.5 shrink-0"/>Reports are cached for fast browsing. Connected default-period reports refresh every six hours; use Refresh for a custom date range. Data & connections explains coverage and provider limitations.</p>
    </>}
  </section>;
}
